---
title: "Estimation"
author: "Paul Stricker"
bibliography: literature_list.bib
date: "2023-11-29"
output: 
 html_document:
      keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(stringr)
library(patchwork)
library(ggplot2)
library(fixest)
library(did)
library(CInf)
library(readxl)
library(gt)
library(xtable)
library(extrafont)

loadfonts(device = "win")
set.seed(100)

#load data
load("port_data_TEU_110.RData")


sample <- c("BEANR", "BEGNE", "BEZEE", "BGVAR", "CYLMS", "DEBRV", "DECUX", "DELBC", "DEHAM", "DEWVN", "DKAAL", "DKAAR", "DKCPH", "DKEBJ", "DKFRC", "EETLL", "ESAGP", "ESALC", "ESALG", "ESBCN", "ESBIO", "ESCAD", "ESCAR", "ESCAS", "ESGIJ",  "ESLPA", "ESMLN", "ESMPG", "ESPMI", "ESSCT", "ESSDR", "ESSVQ", "ESTAR", "ESVGO", "ESVIL", "ESVLC", "FIHEL", "FIHKO", "FIOUL", "FIPOR", "FIRAU", "FRBES", "FRDKK", "FRLEH", "FRMRS", "FRNTE", "GBBEL", "GBBRS", "GBCDF", "GBFOR", "GBFXT", "GBGOO", "GBHUL", "GBIMM", "GBLIV", "GBLON", "GBMED", "GBMME", "GBPME", "GBSOU", "GBWPT", "GRPIR", "GRSKG", "HRPLE", "HRRJK", "IEDRO", "IEDUB", "IEORK", "IEWAT", "ITAOI", "ITBRI", "ITCAG", "ITCTA", "ITCVV", "ITGIT", "ITGOA", "ITLIV", "ITMDC", "ITNAP", "ITRAN", "ITSAL", "ITSPE", "ITSVN", "ITTAR", "ITTRS", "ITVCE", "LTKLJ", "LVRIX", "MEBAR", "MTMAR", "NLAMS", "NLMOE", "NLRTM", "NOKRS", "NOMJF", "NOMSS", "NOOSL", "PLGDN", "PLGDY", "PLSZZ", "PTCNL", "PTFNC", "PTLEI", "PTLIS", "PTPDL", "PTPRV", "PTSET", "PTSIE", "ROCND", "SEGOT", "SEGVX", "SEHAD", "SEHEL", "SEMMA", "SENRK", "SESOE", "SEVST", "SIKOP", "TRAMB", "TRAYT", "TRGEM", "TRISK", "TRIZM", "TRIZT", "TRMER", "TRSSX", "TRTEK")


port_data_TEU <- filter(port_data_TEU, aggregate==0,
                                       stat_port==1,              #filter out non-stat ports (and geographic aggregates)
                                       TEU_yrly >=20000,      #filter out small ports
                                       port_code %in% sample,
                                        period<=105) %>%        
             mutate(s_china = ifelse(sender_code=="CN_X_HK" | sender_code=="HK", 1, 0),
                    port = ifelse(port=="Antwerpen", "Antwerp", port)) %>%
             group_by(port_code, sender_code) %>%
             mutate(pair_id=cur_group_id()) %>% ungroup() %>%
             rename(container=total_TEU)


port_data_agg <- port_data_TEU %>% mutate(origin_china = ifelse(!is.na(container) & (sender_code=="CN_X_HK" | sender_code=="HK"),container,0)) %>%
                               group_by(port, port_code, period, reporter_code, reporter) %>% 
                               summarize(container = sum(container, na.rm=T),
                                         real_gdp_reporter = mean(real_gdp_reporter),
                                         origin_china = sum(origin_china),
                                         group = max(group),
                                         group_operation = max(group_operation),
                                         ownership_china = max(ownership_china),
                                         operation = max(operation),
                                         year = max(year),
                                         quarter = max(quarter)) %>% ungroup() %>%
                              group_by(port_code) %>% 
                              mutate(port_id = cur_group_id(),
                                     mean_container = mean(container, na.rm=T)) %>% ungroup()


#exclude Rotterdam, Amsterdam and treated values for Hamburg
port_data_TEU$container[port_data_TEU$port_code=="NLRTM" & between(port_data_TEU$year,2011,2020)]<-NA
port_data_agg$container[port_data_agg$port_code=="NLRTM" & between(port_data_agg$year,2011,2020)]<-NA


port_data_agg_ny <- port_data_agg %>% filter(group!=0)

port_list <- port_data_agg %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))

port_group_list <- port_data_agg %>% filter(group!=0) %>% group_by(group) %>%
                                     summarize(ports = toString(unique(port)))
port_group_list_op <- port_data_agg %>% filter(group_operation!=0) %>% group_by(group_operation) %>%
                                     summarize(ports = toString(unique(port))) %>% 
                                     rename(group = group_operation)
port_group_list <- rbind(port_group_list, port_group_list_op)
port_group_list <- port_group_list[!duplicated(port_group_list$group),]
port_group_list$ports <- paste(port_group_list$ports,paste("(", port_group_list$group, ")", sep = ""))

# Add Control variables --------------------------------------------------------

load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data.csv")

# control variables
control_var <- merge(wpi_data, terminal_data, by.x="port_code",by.y="port_code", all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      cranes_fixed, cranes_mobile, cranes_floating, max_lift, cargo_depth)


# merge with aggregated data
port_data_agg <- merge(port_data_agg, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 


port_data_agg$quay_length[port_data_agg$quay_length==0] <- 100
port_data_agg$cranes[port_data_agg$cranes==0] <- 1

### Control variables for DID ####
port_data_agg <- port_data_agg %>% group_by(port_code) %>% 
                                   mutate(delta_cranes1y = cranes - cranes[ifelse(row_number()-4<=0,1,row_number()-4)],
                                          delta_cranes5y = cranes - cranes[ifelse(row_number()-20<=0,1,row_number()-20)],
                                          delta_cranes3y = cranes - cranes[ifelse(row_number()-12<=0,1,row_number()-12)],
                                          delta_cranes10y = cranes - cranes[ifelse(row_number()-40<=0,1,row_number()-40)])

controls <- c("quay_length", "max_lift", "cargo_depth")  
var_controls <- c("quay_length")

```




```{r include=FALSE}
spec1 <- feols(container ~ ownership_china  | port_code + period + reporter_code^period,
               data = port_data_agg)
spec2 <- feols(container ~ ownership_china + ownership_china:s_china  | port_code + sender + period,
               data = port_data_TEU)
spec3 <- feols(container ~ ownership_china + ownership_china:s_china | port_code^sender + sender^period,
               data = port_data_TEU)
spec4 <- feols(container ~ ownership_china + ownership_china:s_china  | port_code^sender + sender^period + reporter_code^period,
               data = port_data_TEU)




#set formatting names
setFixest_dict(c(ownership_china = "Ownership Chinese company",
                 s_china = "Origin China",
                 port_code = "Port",
                 period = "Period",
                 reporter_code = "Reporter",
                 sender = "Partner"))

#save table to latex 
cat(esttex(spec1, spec2, spec3, spec4,
                    depvar = FALSE,
                    style.df = style.df(depvar.title = "",
                                        fixef.title = "",
                                        fixef.suffix = "", yesNo = "yes"),
                    vcov = "twoway",
                    adjustbox = TRUE,
                    title = "Fixed effects results",
                    label = "tab:fe_results"
                    #tex = TRUE
           ), file = file.path(getwd(),"results_tables","fe_results.tex"))

#prepare table for Markdownfile
fe_results<- etable(spec1, spec2, spec3, spec4,
                    depvar = FALSE,
                    style.df = style.df(depvar.title = "",
                                        fixef.title = "",
                                        stats.title = "",
                                        fixef.suffix = "", yesNo = "yes"),
                    vcov = "twoway")
colnames(fe_results)[1] <- "col1"

fe_results_gt <- fe_results %>%  
                  gt(rowname_col = "col1") |>
                 tab_header(title = "Fixed effects estimation results",
                            subtitle = "Dependent variable: Total throughput in thousand TEU") |>
              cols_label(
                spec1 = "Eq. 1",
                spec2 = "Eq. 2",
                spec3 = "Eq. 3",
                spec4 = "Eq. 4") |>
              tab_row_group(label = "Fixed effects:",
                            rows = c("Port", "Period", "Reporter-Period", "Partner", "Port-Partner", "Partner-Period"))  |>
              tab_row_group(label = "Diagnostics:",
                            rows = c("S.E.: Clustered", "Observations", "R2", "Within R2")) |>
              row_group_order(groups = c(NA, "Fixed effects:", "Diagnostics:")) |>
  cols_align(align = "center", columns = c("spec1", "spec2", "spec3", "spec4"))



```

```{r include=TRUE, echo=F}
fe_results_gt %>% 
  tab_options(row_group.border.bottom.color = "transparent",
              table_body.hlines.color = "transparent",
              stub.border.width = 0,
              stub.border.color = "transparent",
              row_group.padding = 0) 

        
```


# Difference in Differences


```{r include=F, message=FALSE, warning=FALSE}

#### Estimation ot ATT with never treated as control group ####
attgt <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              #control_group = "not_yet_treated",
                              data = port_data_agg)


attgt_cond <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              data = port_data_agg)



# putting together the results

results1 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt$average_treatment_effect$att,
                                   attgt$groupwise_treatment_effects$att),
                       lower = c(attgt$average_treatment_effect$att - attgt$average_treatment_effect$crit_val,
                                attgt$groupwise_treatment_effects$att - attgt$groupwise_treatment_effects$crit_val),
                       upper = c(attgt$average_treatment_effect$att + attgt$average_treatment_effect$crit_val,
                                  attgt$groupwise_treatment_effects$att + attgt$groupwise_treatment_effects$crit_val),
                       p_value = c(NA, attgt$groupwise_treatment_effects$pre_treatment_p_value))

results2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_cond = c(attgt_cond$average_treatment_effect$att,
                                   attgt_cond$groupwise_treatment_effects$att),
                       lower_cond = c(attgt_cond$average_treatment_effect$att - attgt_cond$average_treatment_effect$crit_val,
                                attgt_cond$groupwise_treatment_effects$att - attgt_cond$groupwise_treatment_effects$crit_val),
                       upper_cond = c(attgt_cond$average_treatment_effect$att + attgt_cond$average_treatment_effect$crit_val,
                                  attgt_cond$groupwise_treatment_effects$att + attgt_cond$groupwise_treatment_effects$crit_val),
                        p_value_cond = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value))

results <- merge(results1, results2, by.x="Estimate", by.y="Estimate", all=T,  sort=F) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      sig_cond = (ATT_cond>0 & lower_cond>0) | (ATT_cond<0 & upper_cond<0),
                      pretest = (p_value < 0.05) & !is.na(p_value),
                      pretest_cond = (p_value_cond < 0.05) & !is.na(p_value_cond),
                      across(c("ATT","ATT_cond","lower","upper","lower_cond","upper_cond"), ~ format(round(.,digits=0), big.mark = ",")),

                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = ifelse(pretest==T, paste0(ATT, "^{x}"),ATT),
                      ATT_cond = ifelse(sig_cond==T, paste0(ATT_cond, "*"), ATT_cond),
                      ATT_cond = ifelse(pretest_cond==T, paste0(ATT_cond, "^{x}"),ATT_cond),
                      Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]"),
                      Conf_cond = paste0("[",str_trim(lower_cond),"; ",str_trim(upper_cond),"]"))
results <- results[c("Estimate", "ATT", "Conf", "ATT_cond", "Conf_cond")]



#### Estimate ATT with not-yet-treated control group ####
attgt_ny <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              control_group = "not_yet_treated",
                              data = port_data_agg)


attgt_cond_ny <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_agg)



# putting together the results

results_ny1 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_ny$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_ny = c(attgt_ny$average_treatment_effect$att,
                                   attgt_ny$groupwise_treatment_effects$att),
                       lower_ny = c(attgt_ny$average_treatment_effect$att - attgt_ny$average_treatment_effect$crit_val,
                                attgt_ny$groupwise_treatment_effects$att - attgt_ny$groupwise_treatment_effects$crit_val),
                       upper_ny = c(attgt_ny$average_treatment_effect$att + attgt_ny$average_treatment_effect$crit_val,
                                  attgt_ny$groupwise_treatment_effects$att + attgt_ny$groupwise_treatment_effects$crit_val),
                       p_value_ny = c(NA, attgt_ny$groupwise_treatment_effects$pre_treatment_p_value))

results_ny2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond_ny$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_cond_ny = c(attgt_cond_ny$average_treatment_effect$att,
                                   attgt_cond_ny$groupwise_treatment_effects$att),
                       lower_cond_ny = c(attgt_cond_ny$average_treatment_effect$att - attgt_cond_ny$average_treatment_effect$crit_val,
                                attgt_cond_ny$groupwise_treatment_effects$att - attgt_cond_ny$groupwise_treatment_effects$crit_val),
                       upper_cond_ny = c(attgt_cond_ny$average_treatment_effect$att + attgt_cond_ny$average_treatment_effect$crit_val,
                                  attgt_cond_ny$groupwise_treatment_effects$att + attgt_cond_ny$groupwise_treatment_effects$crit_val),
                       p_value_cond_ny = c(NA, attgt_cond_ny$groupwise_treatment_effects$pre_treatment_p_value)) 

results_ny <- merge(results_ny1, results_ny2, by.x="Estimate", by.y="Estimate", all=T,  sort=F) %>%
               mutate(sig = (ATT_ny>0 & lower_ny>0) | (ATT_ny<0 & upper_ny<0),
                      sig_cond = (ATT_cond_ny>0 & lower_cond_ny>0) | (ATT_cond_ny<0 & upper_cond_ny<0),
                      pretest = (p_value_ny < 0.05) & !is.na(p_value_ny),
                      pretest_cond = (p_value_cond_ny < 0.05) & !is.na(p_value_cond_ny),
                      across(c("ATT_ny","ATT_cond_ny","lower_ny","upper_ny","lower_cond_ny","upper_cond_ny"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT_ny = ifelse(sig==T, paste0(ATT_ny, "*"), ATT_ny),
                      ATT_ny = ifelse(pretest==T, paste0(ATT_ny, "^{x}"),ATT_ny),
                      ATT_cond_ny = ifelse(sig_cond==T, paste0(ATT_cond_ny, "*"), ATT_cond_ny),
                      ATT_cond_ny = ifelse(pretest_cond==T, paste0(ATT_cond_ny, "^{x}"),ATT_cond_ny),
                      Conf_ny = paste0("[",str_trim(lower_ny),", ",str_trim(upper_ny),"]"),
                      Conf_cond_ny = paste0("[",str_trim(lower_cond_ny),"; ",str_trim(upper_cond_ny),"]"))
results_ny <- results_ny[c("Estimate", "ATT_cond_ny", "Conf_cond_ny")]

results <- merge(results, results_ny, by.x="Estimate", by.y="Estimate", sort=F)


```

```{r include=F}
# generate a Latex table

results_final <- rbind(results[1,],c("by group", rep("", ncol(results)-1)) ,results[2:19,]) 

# Insert multirow cell into the appropriate position in the LaTeX code
addtorow <- list()
addtorow$pos <- list(nrow(results_final),1)
addtorow$command <- c("[2ex] \\hline \\hline \\multicolumn{7}{l}{\\shortstack[l]{Note: Stars indicate that the uniform confidence interval does not include zero.\\\\ Superscript x indicates that we can reject the null of equal average pseudo treatment effects between treated and untreated.}}", 
                      "[1ex]")

# Modify the LaTeX code
latex_code <- print.xtable(xtable(results_final, caption = "Aggregation of group time treatment effects"),
                           label = "tab:did_results",
                           caption.placement = "top",
                           include.rownames = FALSE,
                           add.to.row = addtorow,
                           hline.after = c(-1,-1,0, 2),
                           size = "\\begin{adjustbox}{max width=\\textwidth}")

latex_code <- gsub("Estimate & ATT & Conf & ATT\\\\_cond & Conf\\\\_cond & ATT\\\\_cond\\\\_ny & Conf\\\\_cond\\\\_ny","Control group: & \\\\multicolumn{4}{c}{Never treated} & \\\\multicolumn{2}{c}{Not yet treated} \\\\\\\\\n \\\\cmidrule(lr){2-5} \\\\cmidrule(lr){6-7}  PTA & Uncond. & 95\\\\% CI & Cond. & 95\\\\% CI & Cond. & 95\\\\% CI ", latex_code)

latex_code <- gsub("\\\\end\\{tabular\\}", "\\\\end{tabular} \n \\\\end{adjustbox} \\\\label{tab:did_results}", latex_code)
latex_code <- gsub("by group", "\\\\emph{by group}", latex_code)
latex_code <- gsub("lllllll", "lcccccc", latex_code)
latex_code <- gsub("\\\\verb\\|\\^\\|\\\\\\{x\\\\\\}", "\\\\textsuperscript{x}", latex_code)

# Save modified LaTeX code to a .tex file
cat(latex_code, file = file.path(getwd(), "results_tables", "did_results.tex"))



# generating a gt table
results_gt <- gt(results, rowname_col = "Estimate") |>
              tab_header(
                title = "Aggregation of group time treatment effects",
                subtitle = "Dependent variable: Total throughput in thousand TEU") |>
              cols_label(
                ATT="unconditional",
                ATT_cond="conditional",
                ATT_cond_ny="conditional",
                Conf="95% CI",
                Conf_cond="95% CI",
                Conf_cond_ny="95% CI"
              ) |>
              tab_spanner(label = "Never treated",
                          columns = c("ATT", "Conf", "ATT_cond", "Conf_cond")) |>
              tab_spanner(label = "Not yet treated",
                          columns = c("ATT_cond_ny", "Conf_cond_ny")) |>
              tab_row_group(label = "by group:",
                            rows = c(2:19)) |>
              row_group_order(groups = c(NA,"by group:")) |>
              sub_missing(columns = everything(),
                          rows = everything(),
                          missing_text = "") |>
              tab_footnote(footnote = "Stars indicate that the confidence interval does not include zero.") |>
              tab_options(stub.border.width = 0,
                          table_body.hlines.width = 0
              )


```


```{r include=TRUE, echo=FALSE}
results_gt

```


