---
title: "Reshuffling_direction_region_specific"
author: "Katja Kalkschmied"
date: "2024-05-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE}
library(dplyr)
library(tidyr)
library(writexl)
library(readxl)
library(ggplot2)
library(echoice2)
library(doBy)
library(zoo)
library(fixest)
library(gt)
library(CInf)
library(stringr)
library(xtable)

load("port_data_TEU_out_110.RData")

sample <- c("BEANR", "BEGNE", "BEZEE", "BGVAR", "CYLMS", "DEBRV", "DECUX", "DELBC", "DEHAM", "DEWVN", "DKAAL", "DKAAR", "DKCPH", "DKEBJ", "DKFRC", "EETLL", "ESAGP", "ESALC", "ESALG", "ESBCN", "ESBIO", "ESCAD", "ESCAR", "ESCAS", "ESGIJ",  "ESLPA", "ESMLN", "ESMPG", "ESPMI", "ESSCT", "ESSDR", "ESSVQ", "ESTAR", "ESVGO", "ESVIL", "ESVLC", "FIHEL", "FIHKO", "FIOUL", "FIPOR", "FIRAU", "FRBES", "FRDKK", "FRLEH", "FRMRS", "FRNTE", "GBBEL", "GBBRS", "GBCDF", "GBFOR", "GBFXT", "GBGOO", "GBHUL", "GBIMM", "GBLIV", "GBLON", "GBMED", "GBMME", "GBPME", "GBSOU", "GBWPT", "GRPIR", "GRSKG", "HRPLE", "HRRJK", "IEDRO", "IEDUB", "IEORK", "IEWAT", "ITAOI", "ITBRI", "ITCAG", "ITCTA", "ITCVV", "ITGIT", "ITGOA", "ITLIV", "ITMDC", "ITNAP", "ITRAN", "ITSAL", "ITSPE", "ITSVN", "ITTAR", "ITTRS", "ITVCE", "LTKLJ", "LVRIX", "MEBAR", "MTMAR", "NLAMS", "NLMOE", "NLRTM", "NOKRS", "NOMJF", "NOMSS", "NOOSL", "PLGDN", "PLGDY", "PLSZZ", "PTCNL", "PTFNC", "PTLEI", "PTLIS", "PTPDL", "PTPRV", "PTSET", "PTSIE", "ROCND", "SEGOT", "SEGVX", "SEHAD", "SEHEL", "SEMMA", "SENRK", "SESOE", "SEVST", "SIKOP", "TRAMB", "TRAYT", "TRGEM", "TRISK", "TRIZM", "TRIZT", "TRMER", "TRSSX", "TRTEK")

port_data_TEU_out <- filter(port_data_TEU_out, aggregate==0,
                        stat_port==1,              #filter out non-stat ports (and geographic aggregates)
                        TEU_yrly >=10000,          #filter out small ports
                        port_code %in% sample,
                        period<=105) %>%    
  mutate(s_china = ifelse(sender_code=="CN_X_HK" | sender_code=="HK", 1, 0),
         port = ifelse(port=="Antwerpen", "Antwerp", port)) %>%
  group_by(port_code, sender_code) %>%
  mutate(pair_id=cur_group_id()) %>% ungroup() %>%
  rename(container=total_TEU) %>%
  rename(partner_code=sender_code) %>%
  rename(partner=sender)

# Filter out observations for Rotterdam in the years 2011-2020
port_data_TEU_out <- subset(port_data_TEU_out, !(port == "Rotterdam" & year >= 2011 & year <= 2020))


listpartner <- port_data_TEU_out %>%
  group_by(partner_code) %>%
  slice(1) %>%
  ungroup() %>%
  select(partner_code, partner)


listreporter <- port_data_TEU_out %>%
  group_by(reporter_code) %>%
  slice(1) %>%
  ungroup() %>%
  select(reporter_code, reporter)

partner_region <- read_xlsx("partner_region.xlsx", sheet = "Sheet1")

reporter_region <- merge(listreporter, partner_region, by.x = "reporter_code", by.y = "partner_code", all.x = T) %>% 
  select(reporter_code, partner_region) %>% 
  rename("reporter_region" = "partner_region")

port_data_TEU_out <- merge(port_data_TEU_out,partner_region, by.x = "partner_code", by.y = "partner_code", all.x = T) %>%
  relocate(partner_region, .after = partner_code) %>%
  rename(partner_region=partner_region)
  
port_data_TEU_out <- merge(port_data_TEU_out,reporter_region, by = "reporter_code", all.x = T) %>%
  relocate(reporter_region, .after = reporter_code) 

port_data_TEU_out$NENE_region <- ifelse(port_data_TEU_out$reporter_region == 'NE' & port_data_TEU_out$partner_region == 'NE', 1, 0)
sum(port_data_TEU_out$NENE_region)

port_data_TEU_out$SESE_region <- ifelse(port_data_TEU_out$reporter_region == 'SE' & port_data_TEU_out$partner_region == 'SE', 1, 0)
sum(port_data_TEU_out$SESE_region)

port_data_TEU_out$NESE_region <- ifelse(port_data_TEU_out$reporter_region == 'NE' & port_data_TEU_out$partner_region == 'SE', 1, 0)
sum(port_data_TEU_out$NESE_region)

port_data_TEU_out$SENE_region <- ifelse(port_data_TEU_out$reporter_region == 'SE' & port_data_TEU_out$partner_region == 'NE', 1, 0)
sum(port_data_TEU_out$SENE_region)

port_data_TEU_out$NEEX_region <- ifelse(port_data_TEU_out$reporter_region == 'NE' & port_data_TEU_out$partner_region == 'EX', 1, 0)
sum(port_data_TEU_out$NEEX_region)

port_data_TEU_out$SEEX_region <- ifelse(port_data_TEU_out$reporter_region == 'SE' & port_data_TEU_out$partner_region == 'EX', 1, 0)
sum(port_data_TEU_out$SEEX_region)

region_pair <- ec_undummy(port_data_TEU_out, c('NENE_region', 'SESE_region', 'NESE_region', 'SENE_region','NEEX_region','SEEX_region'), "region_pair", ref_level = "What") %>%
  select(port_code, partner_code, region_pair, year, quarter) 

port_data_TEU_out <- merge(port_data_TEU_out,region_pair, by.x=c("port_code", "partner_code", "year", "quarter"), by.y=c("port_code", "partner_code", "year", "quarter"))

```



```{r include=FALSE, warning=FALSE}

load("port_data_TEU_in_110.RData")

port_data_TEU_in <- filter(port_data_TEU_in, aggregate==0,
                        stat_port==1,              #filter out non-stat ports (and geographic aggregates)
                        TEU_yrly >=10000,          #filter out small ports
                        port_code %in% sample,
                        period<=105) %>%    
  mutate(s_china = ifelse(sender_code=="CN_X_HK" | sender_code=="HK", 1, 0),
         port = ifelse(port=="Antwerpen", "Antwerp", port)) %>%
  group_by(port_code, sender_code) %>%
  mutate(pair_id=cur_group_id()) %>% ungroup() %>%
  rename(container=total_TEU) %>%
  rename(partner_code=sender_code) %>%
  rename(partner=sender)


# Filter out observations for Rotterdam in the years 2011-2020
port_data_TEU_in <- subset(port_data_TEU_in, !(port == "Rotterdam" & year >= 2011 & year <= 2020))

listpartner <- port_data_TEU_in %>%
  group_by(partner_code) %>%
  slice(1) %>%
  ungroup() %>%
  select(partner_code, partner)


listreporter <- port_data_TEU_in %>%
  group_by(reporter_code) %>%
  slice(1) %>%
  ungroup() %>%
  select(reporter_code, reporter)

partner_region <- read_xlsx("partner_region.xlsx", sheet = "Sheet1")

reporter_region <- merge(listreporter, partner_region, by.x = "reporter_code", by.y = "partner_code", all.x = T) %>% 
  select(reporter_code, partner_region) %>% 
  rename("reporter_region" = "partner_region")

port_data_TEU_in <- merge(port_data_TEU_in,partner_region, by.x = "partner_code", by.y = "partner_code", all.x = T) %>%
  relocate(partner_region, .after = partner_code) %>%
  rename(partner_region=partner_region)
  
port_data_TEU_in <- merge(port_data_TEU_in,reporter_region, by = "reporter_code", all.x = T) %>%
  relocate(reporter_region, .after = reporter_code) 

port_data_TEU_in$NENE_region <- ifelse(port_data_TEU_in$reporter_region == 'NE' & port_data_TEU_in$partner_region == 'NE', 1, 0)
sum(port_data_TEU_in$NENE_region)

port_data_TEU_in$SESE_region <- ifelse(port_data_TEU_in$reporter_region == 'SE' & port_data_TEU_in$partner_region == 'SE', 1, 0)
sum(port_data_TEU_in$SESE_region)

port_data_TEU_in$NESE_region <- ifelse(port_data_TEU_in$reporter_region == 'NE' & port_data_TEU_in$partner_region == 'SE', 1, 0)
sum(port_data_TEU_in$NESE_region)

port_data_TEU_in$SENE_region <- ifelse(port_data_TEU_in$reporter_region == 'SE' & port_data_TEU_in$partner_region == 'NE', 1, 0)
sum(port_data_TEU_in$SENE_region)

port_data_TEU_in$NEEX_region <- ifelse(port_data_TEU_in$reporter_region == 'NE' & port_data_TEU_in$partner_region == 'EX', 1, 0)
sum(port_data_TEU_in$NEEX_region)

port_data_TEU_in$SEEX_region <- ifelse(port_data_TEU_in$reporter_region == 'SE' & port_data_TEU_in$partner_region == 'EX', 1, 0)
sum(port_data_TEU_in$SEEX_region)

region_pair <- ec_undummy(port_data_TEU_in, c('NENE_region', 'SESE_region', 'NESE_region', 'SENE_region','NEEX_region','SEEX_region'), "region_pair", ref_level = "What") %>%
  select(port_code, partner_code, region_pair, year, quarter) 

port_data_TEU_in <- merge(port_data_TEU_in,region_pair, by.x=c("port_code", "partner_code", "year", "quarter"), by.y=c("port_code", "partner_code", "year", "quarter"))
```

# Inflows from extern

```{r include=FALSE, warning=FALSE}
set.seed(100)

port_data_in <- port_data_TEU_in %>% 
  filter(region_pair=="NEEX_region" | region_pair=="SEEX_region") %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container=mean(container))

port_data_agg_in <- port_data_in %>% mutate(origin_china = ifelse(!is.na(container) & (partner_code=="CN_X_HK" | partner_code=="HK"),container,0)) %>%
  group_by(port, port_code, period, reporter_code) %>% 
  summarize(container = sum(container, na.rm=T),
            real_gdp_reporter = mean(real_gdp_reporter),
            origin_china = sum(origin_china),
            group = max(group),
            group_operation = max(group_operation),
            ownership_china = max(ownership_china),
            operation = max(operation),
            year = max(year),
            quarter = max(quarter)) %>% ungroup() %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container = mean(container, na.rm=T)) %>% ungroup()

# add terminal data to the data set
load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data2.csv")                      # new historical information

# WPI control variables new
control_var <- merge(wpi_data, terminal_data, by=c("port_code", "year"), all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      #cranes_fixed, cranes_mobile, cranes_floating, 
                      max_lift, cargo_depth,
                      cosco_length) %>% arrange(port_code, desc(year)) %>% group_by(port_code) %>%
               fill(c("max_lift", "cargo_depth"), .direction = "downup")


# merge with aggregated data
port_data_agg_in <- merge(port_data_agg_in, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 

# market size controls 
markets <- read.csv(file.path(getwd(),"control variables_new", "markets.csv"))

# markets data does not need interpolation, as we only gathered it for years with treatment
port_data_agg_in  <- merge(port_data_agg_in , markets[,c("port_code", "year", "local_markets", "foreign_markets", "all_markets")], by.x=c("port_code", "year"), by.y = c("port_code", "year"), all.x=T) %>% arrange(port_code, desc(period)) %>% group_by(port_code) %>% fill(c("local_markets", "local_markets", "foreign_markets", "all_markets"), .direction = "downup")

# TENtec infrastructure variables
TENtec <- read.csv(file.path(getwd(),"control variables_new", "TENtec_corridors.csv"))       # on port_code level 

port_data_agg_in  <- merge(port_data_agg_in , TENtec[,c("port_code", "node.score", "TENtec.core.port")], by.x=c("port_code"), by.y = c("port_code"), all.x=T)

# no zeros allowed in controlvariables
port_data_agg_in$quay_length[port_data_agg_in$quay_length==0] <- 100
port_data_agg_in$cranes[port_data_agg_in$cranes==0] <- 1


### Control variables for DID ####

controls <- c("quay_length", "local_markets", "foreign_markets", "node.score", "cargo_depth")
var_controls <- c("quay_length")




### Produce treated ports list for results presentation
port_list <- port_data_agg_in %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))


#### Estimation ot ATT with never treated as control group ####
attgt <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              data = port_data_agg_in)


attgt_cond <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_agg_in)



# putting together the results

results1 <-  data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt$average_treatment_effect$att,
                                   attgt$groupwise_treatment_effects$att),
                       lower = c(attgt$average_treatment_effect$att - attgt$average_treatment_effect$crit_val,
                                attgt$groupwise_treatment_effects$att - attgt$groupwise_treatment_effects$crit_val),
                       upper = c(attgt$average_treatment_effect$att + attgt$average_treatment_effect$crit_val,
                                  attgt$groupwise_treatment_effects$att + attgt$groupwise_treatment_effects$crit_val),
                       p_value_left = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_cond = c(attgt_cond$average_treatment_effect$att,
                                   attgt_cond$groupwise_treatment_effects$att),
                       lower_cond = c(attgt_cond$average_treatment_effect$att - attgt_cond$average_treatment_effect$crit_val,
                                attgt_cond$groupwise_treatment_effects$att - attgt_cond$groupwise_treatment_effects$crit_val),
                       upper_cond = c(attgt_cond$average_treatment_effect$att + attgt_cond$average_treatment_effect$crit_val,
                                  attgt_cond$groupwise_treatment_effects$att + attgt_cond$groupwise_treatment_effects$crit_val),
                         p_value_left_cond = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results <- merge(results1, results2, by.x="Estimate", by.y="Estimate", all=T,  sort=F) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      sig_cond = (ATT_cond>0 & lower_cond>0) | (ATT_cond<0 & upper_cond<0),
                      pretest_left = (p_value_left < 0.05) & !is.na(p_value_left),
                      pretest_right = (p_value_left > 0.95) & !is.na(p_value_left),
                      pretest_left_cond = (p_value_left_cond < 0.05) & !is.na(p_value_left_cond),
                      pretest_right_cond = (p_value_left_cond > 0.95) & !is.na(p_value_left_cond),
                      across(c("ATT","ATT_cond","lower","upper","lower_cond","upper_cond"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = case_when(pretest_left==T ~ paste0(ATT, "^{+}"),
                                              pretest_right==T ~ paste0(ATT, "^{-}"),
                                              .default = ATT),
                      ATT_cond = ifelse(sig_cond==T, paste0(ATT_cond, "*"), ATT_cond),
                      ATT_cond = case_when(pretest_left_cond==T ~ paste0(ATT_cond, "^{+}"),
                                              pretest_right_cond==T ~ paste0(ATT_cond, "^{-}"),
                                              .default = ATT),
                      Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]"),
                      Conf_cond = paste0("[",str_trim(lower_cond),"; ",str_trim(upper_cond),"]"))

results_1 <- results[c("Estimate", "ATT", "Conf", "ATT_cond", "Conf_cond")]

results_1

```

# Outflows to the other region

```{r include=FALSE, warning=FALSE}
set.seed(100)

port_data_out <- port_data_TEU_out %>% 
  filter(region_pair=="NESE_region" | region_pair=="SENE_region") %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container=mean(container))

port_data_agg_out <- port_data_out %>% mutate(origin_china = ifelse(!is.na(container) & (partner_code=="CN_X_HK" | partner_code=="HK"),container,0)) %>%
  group_by(port, port_code, period, reporter_code) %>% 
  summarize(container = sum(container, na.rm=T),
            real_gdp_reporter = mean(real_gdp_reporter),
            origin_china = sum(origin_china),
            group = max(group),
            group_operation = max(group_operation),
            ownership_china = max(ownership_china),
            operation = max(operation),
            year = max(year),
            quarter = max(quarter)) %>% ungroup() %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container = mean(container, na.rm=T)) %>% ungroup()

# add terminal data to the data set
load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data2.csv")                      # new historical information

# WPI control variables new
control_var <- merge(wpi_data, terminal_data, by=c("port_code", "year"), all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      #cranes_fixed, cranes_mobile, cranes_floating, 
                      max_lift, cargo_depth,
                      cosco_length) %>% arrange(port_code, desc(year)) %>% group_by(port_code) %>%
               fill(c("max_lift", "cargo_depth"), .direction = "downup")


# merge with aggregated data
port_data_agg_out <- merge(port_data_agg_out, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 

# market size controls 
markets <- read.csv(file.path(getwd(),"control variables_new", "markets.csv"))

# markets data does not need interpolation, as we only gathered it for years with treatment
port_data_agg_out  <- merge(port_data_agg_out , markets[,c("port_code", "year", "local_markets", "foreign_markets", "all_markets")], by.x=c("port_code", "year"), by.y = c("port_code", "year"), all.x=T) %>% arrange(port_code, desc(period)) %>% group_by(port_code) %>% fill(c("local_markets", "local_markets", "foreign_markets", "all_markets"), .direction = "downup")

# TENtec infrastructure variables
TENtec <- read.csv(file.path(getwd(),"control variables_new", "TENtec_corridors.csv"))       # on port_code level 

port_data_agg_out  <- merge(port_data_agg_out , TENtec[,c("port_code", "node.score", "TENtec.core.port")], by.x=c("port_code"), by.y = c("port_code"), all.x=T)

# no zeros allowed in controlvariables
port_data_agg_out$quay_length[port_data_agg_out$quay_length==0] <- 100
port_data_agg_out$cranes[port_data_agg_out$cranes==0] <- 1


### Control variables for DID ####

controls <- c("quay_length", "local_markets", "foreign_markets", "node.score", "cargo_depth")
var_controls <- c("quay_length")


### Produce treated ports list for results presentation
port_list <- port_data_agg_out %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))


#### Estimation ot ATT with never treated as control group ####
attgt <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              #xformula = c("ships"),
                              #varformula = c("ships"),
                              #control_group = "not_yet_treated",
                              data = port_data_agg_out)


attgt_cond <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_agg_out)


# putting together the results

results1 <-  data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt$average_treatment_effect$att,
                                   attgt$groupwise_treatment_effects$att),
                       lower = c(attgt$average_treatment_effect$att - attgt$average_treatment_effect$crit_val,
                                attgt$groupwise_treatment_effects$att - attgt$groupwise_treatment_effects$crit_val),
                       upper = c(attgt$average_treatment_effect$att + attgt$average_treatment_effect$crit_val,
                                  attgt$groupwise_treatment_effects$att + attgt$groupwise_treatment_effects$crit_val),
                       p_value_left = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_cond = c(attgt_cond$average_treatment_effect$att,
                                   attgt_cond$groupwise_treatment_effects$att),
                       lower_cond = c(attgt_cond$average_treatment_effect$att - attgt_cond$average_treatment_effect$crit_val,
                                attgt_cond$groupwise_treatment_effects$att - attgt_cond$groupwise_treatment_effects$crit_val),
                       upper_cond = c(attgt_cond$average_treatment_effect$att + attgt_cond$average_treatment_effect$crit_val,
                                  attgt_cond$groupwise_treatment_effects$att + attgt_cond$groupwise_treatment_effects$crit_val),
                         p_value_left_cond = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results <- merge(results1, results2, by.x="Estimate", by.y="Estimate", all=T,  sort=F) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      sig_cond = (ATT_cond>0 & lower_cond>0) | (ATT_cond<0 & upper_cond<0),
                      pretest_left = (p_value_left < 0.05) & !is.na(p_value_left),
                      pretest_right = (p_value_left > 0.95) & !is.na(p_value_left),
                      pretest_left_cond = (p_value_left_cond < 0.05) & !is.na(p_value_left_cond),
                      pretest_right_cond = (p_value_left_cond > 0.95) & !is.na(p_value_left_cond),
                      across(c("ATT","ATT_cond","lower","upper","lower_cond","upper_cond"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = case_when(pretest_left==T ~ paste0(ATT, "^{+}"),
                                              pretest_right==T ~ paste0(ATT, "^{-}"),
                                              .default = ATT),
                      ATT_cond = ifelse(sig_cond==T, paste0(ATT_cond, "*"), ATT_cond),
                      ATT_cond = case_when(pretest_left_cond==T ~ paste0(ATT_cond, "^{+}"),
                                              pretest_right_cond==T ~ paste0(ATT_cond, "^{-}"),
                                              .default = ATT),
                      Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]"),
                      Conf_cond = paste0("[",str_trim(lower_cond),"; ",str_trim(upper_cond),"]"))

results_2 <- results[c("Estimate", "ATT", "Conf", "ATT_cond", "Conf_cond")]

results_2

```

# Outflows to within the region

```{r include=FALSE, warning=FALSE}
set.seed(100)

port_data_out <- port_data_TEU_out %>% 
  filter(region_pair=="NENE_region" | region_pair=="SESE_region") %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container=mean(container))

port_data_agg_out <- port_data_out %>% mutate(origin_china = ifelse(!is.na(container) & (partner_code=="CN_X_HK" | partner_code=="HK"),container,0)) %>%
  group_by(port, port_code, period, reporter_code) %>% 
  summarize(container = sum(container, na.rm=T),
            real_gdp_reporter = mean(real_gdp_reporter),
            origin_china = sum(origin_china),
            group = max(group),
            group_operation = max(group_operation),
            ownership_china = max(ownership_china),
            operation = max(operation),
            year = max(year),
            quarter = max(quarter)) %>% ungroup() %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container = mean(container, na.rm=T)) %>% ungroup()

# add terminal data to the data set
load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data2.csv")                      # new historical information

# WPI control variables new
control_var <- merge(wpi_data, terminal_data, by=c("port_code", "year"), all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      #cranes_fixed, cranes_mobile, cranes_floating, 
                      max_lift, cargo_depth,
                      cosco_length) %>% arrange(port_code, desc(year)) %>% group_by(port_code) %>%
               fill(c("max_lift", "cargo_depth"), .direction = "downup")


# merge with aggregated data
port_data_agg_out <- merge(port_data_agg_out, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 

# market size controls 
markets <- read.csv(file.path(getwd(),"control variables_new", "markets.csv"))

# markets data does not need interpolation, as we only gathered it for years with treatment
port_data_agg_out  <- merge(port_data_agg_out , markets[,c("port_code", "year", "local_markets", "foreign_markets", "all_markets")], by.x=c("port_code", "year"), by.y = c("port_code", "year"), all.x=T) %>% arrange(port_code, desc(period)) %>% group_by(port_code) %>% fill(c("local_markets", "local_markets", "foreign_markets", "all_markets"), .direction = "downup")

# TENtec infrastructure variables
TENtec <- read.csv(file.path(getwd(),"control variables_new", "TENtec_corridors.csv"))       # on port_code level 

port_data_agg_out  <- merge(port_data_agg_out , TENtec[,c("port_code", "node.score", "TENtec.core.port")], by.x=c("port_code"), by.y = c("port_code"), all.x=T)

# no zeros allowed in controlvariables
port_data_agg_out$quay_length[port_data_agg_out$quay_length==0] <- 100
port_data_agg_out$cranes[port_data_agg_out$cranes==0] <- 1


### Control variables for DID ####

controls <- c("quay_length", "local_markets", "foreign_markets", "node.score", "cargo_depth")
var_controls <- c("quay_length")


### Produce treated ports list for results presentation
port_list <- port_data_agg_out %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))


#### Estimation ot ATT with never treated as control group ####
attgt <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              data = port_data_agg_out)


attgt_cond <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_agg_out)



# putting together the results

results1 <-  data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt$average_treatment_effect$att,
                                   attgt$groupwise_treatment_effects$att),
                       lower = c(attgt$average_treatment_effect$att - attgt$average_treatment_effect$crit_val,
                                attgt$groupwise_treatment_effects$att - attgt$groupwise_treatment_effects$crit_val),
                       upper = c(attgt$average_treatment_effect$att + attgt$average_treatment_effect$crit_val,
                                  attgt$groupwise_treatment_effects$att + attgt$groupwise_treatment_effects$crit_val),
                       p_value_left = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_cond = c(attgt_cond$average_treatment_effect$att,
                                   attgt_cond$groupwise_treatment_effects$att),
                       lower_cond = c(attgt_cond$average_treatment_effect$att - attgt_cond$average_treatment_effect$crit_val,
                                attgt_cond$groupwise_treatment_effects$att - attgt_cond$groupwise_treatment_effects$crit_val),
                       upper_cond = c(attgt_cond$average_treatment_effect$att + attgt_cond$average_treatment_effect$crit_val,
                                  attgt_cond$groupwise_treatment_effects$att + attgt_cond$groupwise_treatment_effects$crit_val),
                         p_value_left_cond = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results <- merge(results1, results2, by.x="Estimate", by.y="Estimate", all=T,  sort=F) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      sig_cond = (ATT_cond>0 & lower_cond>0) | (ATT_cond<0 & upper_cond<0),
                      pretest_left = (p_value_left < 0.05) & !is.na(p_value_left),
                      pretest_right = (p_value_left > 0.95) & !is.na(p_value_left),
                      pretest_left_cond = (p_value_left_cond < 0.05) & !is.na(p_value_left_cond),
                      pretest_right_cond = (p_value_left_cond > 0.95) & !is.na(p_value_left_cond),
                      across(c("ATT","ATT_cond","lower","upper","lower_cond","upper_cond"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = case_when(pretest_left==T ~ paste0(ATT, "^{+}"),
                                              pretest_right==T ~ paste0(ATT, "^{-}"),
                                              .default = ATT),
                      ATT_cond = ifelse(sig_cond==T, paste0(ATT_cond, "*"), ATT_cond),
                      ATT_cond = case_when(pretest_left_cond==T ~ paste0(ATT_cond, "^{+}"),
                                              pretest_right_cond==T ~ paste0(ATT_cond, "^{-}"),
                                              .default = ATT),
                      Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]"),
                      Conf_cond = paste0("[",str_trim(lower_cond),"; ",str_trim(upper_cond),"]"))

results_3 <- results[c("Estimate", "ATT", "Conf", "ATT_cond", "Conf_cond")]


results_3
```

# Inflows from within the regions

```{r include=FALSE, warning=FALSE}
set.seed(100)

port_data_in <- port_data_TEU_in %>% 
  filter(region_pair=="SESE_region" | region_pair=="NENE_region") %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container=mean(container))

port_data_agg_in <- port_data_in %>% mutate(origin_china = ifelse(!is.na(container) & (partner_code=="CN_X_HK" | partner_code=="HK"),container,0)) %>%
  group_by(port, port_code, period, reporter_code) %>% 
  summarize(container = sum(container, na.rm=T),
            real_gdp_reporter = mean(real_gdp_reporter),
            origin_china = sum(origin_china),
            group = max(group),
            group_operation = max(group_operation),
            ownership_china = max(ownership_china),
            operation = max(operation),
            year = max(year),
            quarter = max(quarter)) %>% ungroup() %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container = mean(container, na.rm=T)) %>% ungroup()

# add terminal data to the data set
load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data2.csv")                      # new historical information

# WPI control variables new
control_var <- merge(wpi_data, terminal_data, by=c("port_code", "year"), all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      #cranes_fixed, cranes_mobile, cranes_floating, 
                      max_lift, cargo_depth,
                      cosco_length) %>% arrange(port_code, desc(year)) %>% group_by(port_code) %>%
               fill(c("max_lift", "cargo_depth"), .direction = "downup")


# merge with aggregated data
port_data_agg_in <- merge(port_data_agg_in, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 

# market size controls 
markets <- read.csv(file.path(getwd(),"control variables_new", "markets.csv"))

# markets data does not need interpolation, as we only gathered it for years with treatment
port_data_agg_in  <- merge(port_data_agg_in , markets[,c("port_code", "year", "local_markets", "foreign_markets", "all_markets")], by.x=c("port_code", "year"), by.y = c("port_code", "year"), all.x=T) %>% arrange(port_code, desc(period)) %>% group_by(port_code) %>% fill(c("local_markets", "local_markets", "foreign_markets", "all_markets"), .direction = "downup")

# TENtec infrastructure variables
TENtec <- read.csv(file.path(getwd(),"control variables_new", "TENtec_corridors.csv"))       # on port_code level 

port_data_agg_in  <- merge(port_data_agg_in , TENtec[,c("port_code", "node.score", "TENtec.core.port")], by.x=c("port_code"), by.y = c("port_code"), all.x=T)

# no zeros allowed in controlvariables
port_data_agg_in$quay_length[port_data_agg_in$quay_length==0] <- 100
port_data_agg_in$cranes[port_data_agg_in$cranes==0] <- 1


### Control variables for DID ####

controls <- c("quay_length", "local_markets", "foreign_markets", "node.score", "cargo_depth")
var_controls <- c("quay_length")


### Produce treated ports list for results presentation
port_list <- port_data_agg_in %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))


#### Estimation ot ATT with never treated as control group ####
attgt <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              data = port_data_agg_in)


attgt_cond <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_agg_in)



# putting together the results

results1 <-  data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt$average_treatment_effect$att,
                                   attgt$groupwise_treatment_effects$att),
                       lower = c(attgt$average_treatment_effect$att - attgt$average_treatment_effect$crit_val,
                                attgt$groupwise_treatment_effects$att - attgt$groupwise_treatment_effects$crit_val),
                       upper = c(attgt$average_treatment_effect$att + attgt$average_treatment_effect$crit_val,
                                  attgt$groupwise_treatment_effects$att + attgt$groupwise_treatment_effects$crit_val),
                       p_value_left = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_cond = c(attgt_cond$average_treatment_effect$att,
                                   attgt_cond$groupwise_treatment_effects$att),
                       lower_cond = c(attgt_cond$average_treatment_effect$att - attgt_cond$average_treatment_effect$crit_val,
                                attgt_cond$groupwise_treatment_effects$att - attgt_cond$groupwise_treatment_effects$crit_val),
                       upper_cond = c(attgt_cond$average_treatment_effect$att + attgt_cond$average_treatment_effect$crit_val,
                                  attgt_cond$groupwise_treatment_effects$att + attgt_cond$groupwise_treatment_effects$crit_val),
                         p_value_left_cond = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results <- merge(results1, results2, by.x="Estimate", by.y="Estimate", all=T,  sort=F) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      sig_cond = (ATT_cond>0 & lower_cond>0) | (ATT_cond<0 & upper_cond<0),
                      pretest_left = (p_value_left < 0.05) & !is.na(p_value_left),
                      pretest_right = (p_value_left > 0.95) & !is.na(p_value_left),
                      pretest_left_cond = (p_value_left_cond < 0.05) & !is.na(p_value_left_cond),
                      pretest_right_cond = (p_value_left_cond > 0.95) & !is.na(p_value_left_cond),
                      across(c("ATT","ATT_cond","lower","upper","lower_cond","upper_cond"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = case_when(pretest_left==T ~ paste0(ATT, "^{+}"),
                                              pretest_right==T ~ paste0(ATT, "^{-}"),
                                              .default = ATT),
                      ATT_cond = ifelse(sig_cond==T, paste0(ATT_cond, "*"), ATT_cond),
                      ATT_cond = case_when(pretest_left_cond==T ~ paste0(ATT_cond, "^{+}"),
                                              pretest_right_cond==T ~ paste0(ATT_cond, "^{-}"),
                                              .default = ATT),
                      Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]"),
                      Conf_cond = paste0("[",str_trim(lower_cond),"; ",str_trim(upper_cond),"]"))

results_4 <- results[c("Estimate", "ATT", "Conf", "ATT_cond", "Conf_cond")]

```

# Inflows from other regions

```{r include=FALSE, warning=FALSE}
set.seed(100)

port_data_in <- port_data_TEU_in %>% 
  filter(region_pair=="NESE_region" | region_pair=="SENE_region") %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container=mean(container))

port_data_agg_in <- port_data_in %>% mutate(origin_china = ifelse(!is.na(container) & (partner_code=="CN_X_HK" | partner_code=="HK"),container,0)) %>%
  group_by(port, port_code, period, reporter_code) %>% 
  summarize(container = sum(container, na.rm=T),
            real_gdp_reporter = mean(real_gdp_reporter),
            origin_china = sum(origin_china),
            group = max(group),
            group_operation = max(group_operation),
            ownership_china = max(ownership_china),
            operation = max(operation),
            year = max(year),
            quarter = max(quarter)) %>% ungroup() %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container = mean(container, na.rm=T)) %>% ungroup()

# add terminal data to the data set
load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data2.csv")                      # new historical information

# WPI control variables new
control_var <- merge(wpi_data, terminal_data, by=c("port_code", "year"), all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      #cranes_fixed, cranes_mobile, cranes_floating, 
                      max_lift, cargo_depth,
                      cosco_length) %>% arrange(port_code, desc(year)) %>% group_by(port_code) %>%
               fill(c("max_lift", "cargo_depth"), .direction = "downup")


# merge with aggregated data
port_data_agg_in <- merge(port_data_agg_in, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 

# market size controls 
markets <- read.csv(file.path(getwd(),"control variables_new", "markets.csv"))

# markets data does not need interpolation, as we only gathered it for years with treatment
port_data_agg_in  <- merge(port_data_agg_in , markets[,c("port_code", "year", "local_markets", "foreign_markets", "all_markets")], by.x=c("port_code", "year"), by.y = c("port_code", "year"), all.x=T) %>% arrange(port_code, desc(period)) %>% group_by(port_code) %>% fill(c("local_markets", "local_markets", "foreign_markets", "all_markets"), .direction = "downup")

# TENtec infrastructure variables
TENtec <- read.csv(file.path(getwd(),"control variables_new", "TENtec_corridors.csv"))       # on port_code level 

port_data_agg_in  <- merge(port_data_agg_in , TENtec[,c("port_code", "node.score", "TENtec.core.port")], by.x=c("port_code"), by.y = c("port_code"), all.x=T)

# no zeros allowed in controlvariables
port_data_agg_in$quay_length[port_data_agg_in$quay_length==0] <- 100
port_data_agg_in$cranes[port_data_agg_in$cranes==0] <- 1


### Control variables for DID ####

controls <- c("quay_length", "local_markets", "foreign_markets", "node.score", "cargo_depth")
var_controls <- c("quay_length")


### Produce treated ports list for results presentation
port_list <- port_data_agg_in %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))


#### Estimation ot ATT with never treated as control group ####
attgt <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              data = port_data_agg_in)


attgt_cond <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_agg_in)



# putting together the results

results1 <-  data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt$average_treatment_effect$att,
                                   attgt$groupwise_treatment_effects$att),
                       lower = c(attgt$average_treatment_effect$att - attgt$average_treatment_effect$crit_val,
                                attgt$groupwise_treatment_effects$att - attgt$groupwise_treatment_effects$crit_val),
                       upper = c(attgt$average_treatment_effect$att + attgt$average_treatment_effect$crit_val,
                                  attgt$groupwise_treatment_effects$att + attgt$groupwise_treatment_effects$crit_val),
                       p_value_left = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_cond = c(attgt_cond$average_treatment_effect$att,
                                   attgt_cond$groupwise_treatment_effects$att),
                       lower_cond = c(attgt_cond$average_treatment_effect$att - attgt_cond$average_treatment_effect$crit_val,
                                attgt_cond$groupwise_treatment_effects$att - attgt_cond$groupwise_treatment_effects$crit_val),
                       upper_cond = c(attgt_cond$average_treatment_effect$att + attgt_cond$average_treatment_effect$crit_val,
                                  attgt_cond$groupwise_treatment_effects$att + attgt_cond$groupwise_treatment_effects$crit_val),
                         p_value_left_cond = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results <- merge(results1, results2, by.x="Estimate", by.y="Estimate", all=T,  sort=F) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      sig_cond = (ATT_cond>0 & lower_cond>0) | (ATT_cond<0 & upper_cond<0),
                      pretest_left = (p_value_left < 0.05) & !is.na(p_value_left),
                      pretest_right = (p_value_left > 0.95) & !is.na(p_value_left),
                      pretest_left_cond = (p_value_left_cond < 0.05) & !is.na(p_value_left_cond),
                      pretest_right_cond = (p_value_left_cond > 0.95) & !is.na(p_value_left_cond),
                      across(c("ATT","ATT_cond","lower","upper","lower_cond","upper_cond"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = case_when(pretest_left==T ~ paste0(ATT, "^{+}"),
                                              pretest_right==T ~ paste0(ATT, "^{-}"),
                                              .default = ATT),
                      ATT_cond = ifelse(sig_cond==T, paste0(ATT_cond, "*"), ATT_cond),
                      ATT_cond = case_when(pretest_left_cond==T ~ paste0(ATT_cond, "^{+}"),
                                              pretest_right_cond==T ~ paste0(ATT_cond, "^{-}"),
                                              .default = ATT),
                      Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]"),
                      Conf_cond = paste0("[",str_trim(lower_cond),"; ",str_trim(upper_cond),"]"))

results_5 <- results[c("Estimate", "ATT", "Conf", "ATT_cond", "Conf_cond")]
```

# Outflows to extern

```{r include=FALSE, warning=FALSE}
set.seed(100)

port_data_out <- port_data_TEU_out %>% 
  filter(region_pair=="NEEX_region" | region_pair=="SEEX_region") %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container=mean(container))

port_data_agg_out <- port_data_out %>% mutate(origin_china = ifelse(!is.na(container) & (partner_code=="CN_X_HK" | partner_code=="HK"),container,0)) %>%
  group_by(port, port_code, period, reporter_code) %>% 
  summarize(container = sum(container, na.rm=T),
            real_gdp_reporter = mean(real_gdp_reporter),
            origin_china = sum(origin_china),
            group = max(group),
            group_operation = max(group_operation),
            ownership_china = max(ownership_china),
            operation = max(operation),
            year = max(year),
            quarter = max(quarter)) %>% ungroup() %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container = mean(container, na.rm=T)) %>% ungroup()

# add terminal data to the data set
load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data2.csv")                      # new historical information

# WPI control variables new
control_var <- merge(wpi_data, terminal_data, by=c("port_code", "year"), all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      #cranes_fixed, cranes_mobile, cranes_floating, 
                      max_lift, cargo_depth,
                      cosco_length) %>% arrange(port_code, desc(year)) %>% group_by(port_code) %>%
               fill(c("max_lift", "cargo_depth"), .direction = "downup")


# merge with aggregated data
port_data_agg_out <- merge(port_data_agg_out, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 

# market size controls 
markets <- read.csv(file.path(getwd(),"control variables_new", "markets.csv"))

# markets data does not need interpolation, as we only gathered it for years with treatment
port_data_agg_out  <- merge(port_data_agg_out , markets[,c("port_code", "year", "local_markets", "foreign_markets", "all_markets")], by.x=c("port_code", "year"), by.y = c("port_code", "year"), all.x=T) %>% arrange(port_code, desc(period)) %>% group_by(port_code) %>% fill(c("local_markets", "local_markets", "foreign_markets", "all_markets"), .direction = "downup")

# TENtec infrastructure variables
TENtec <- read.csv(file.path(getwd(),"control variables_new", "TENtec_corridors.csv"))       # on port_code level 

port_data_agg_out  <- merge(port_data_agg_out , TENtec[,c("port_code", "node.score", "TENtec.core.port")], by.x=c("port_code"), by.y = c("port_code"), all.x=T)

# no zeros allowed in controlvariables
port_data_agg_out$quay_length[port_data_agg_out$quay_length==0] <- 100
port_data_agg_out$cranes[port_data_agg_out$cranes==0] <- 1


### Control variables for DID ####

controls <- c("quay_length", "local_markets", "foreign_markets", "node.score", "cargo_depth")
var_controls <- c("quay_length")


### Produce treated ports list for results presentation
port_list <- port_data_agg_out %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))


#### Estimation ot ATT with never treated as control group ####
attgt <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              data = port_data_agg_out)


attgt_cond <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_agg_out)



# putting together the results

results1 <-  data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt$average_treatment_effect$att,
                                   attgt$groupwise_treatment_effects$att),
                       lower = c(attgt$average_treatment_effect$att - attgt$average_treatment_effect$crit_val,
                                attgt$groupwise_treatment_effects$att - attgt$groupwise_treatment_effects$crit_val),
                       upper = c(attgt$average_treatment_effect$att + attgt$average_treatment_effect$crit_val,
                                  attgt$groupwise_treatment_effects$att + attgt$groupwise_treatment_effects$crit_val),
                       p_value_left = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond$groupwise_treatment_effects$id), port_list$id)]),
                       ATT_cond = c(attgt_cond$average_treatment_effect$att,
                                   attgt_cond$groupwise_treatment_effects$att),
                       lower_cond = c(attgt_cond$average_treatment_effect$att - attgt_cond$average_treatment_effect$crit_val,
                                attgt_cond$groupwise_treatment_effects$att - attgt_cond$groupwise_treatment_effects$crit_val),
                       upper_cond = c(attgt_cond$average_treatment_effect$att + attgt_cond$average_treatment_effect$crit_val,
                                  attgt_cond$groupwise_treatment_effects$att + attgt_cond$groupwise_treatment_effects$crit_val),
                         p_value_left_cond = c(NA, attgt_cond$groupwise_treatment_effects$pre_treatment_p_value_left))

results <- merge(results1, results2, by.x="Estimate", by.y="Estimate", all=T,  sort=F) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      sig_cond = (ATT_cond>0 & lower_cond>0) | (ATT_cond<0 & upper_cond<0),
                      pretest_left = (p_value_left < 0.05) & !is.na(p_value_left),
                      pretest_right = (p_value_left > 0.95) & !is.na(p_value_left),
                      pretest_left_cond = (p_value_left_cond < 0.05) & !is.na(p_value_left_cond),
                      pretest_right_cond = (p_value_left_cond > 0.95) & !is.na(p_value_left_cond),
                      across(c("ATT","ATT_cond","lower","upper","lower_cond","upper_cond"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = case_when(pretest_left==T ~ paste0(ATT, "^{+}"),
                                              pretest_right==T ~ paste0(ATT, "^{-}"),
                                              .default = ATT),
                      ATT_cond = ifelse(sig_cond==T, paste0(ATT_cond, "*"), ATT_cond),
                      ATT_cond = case_when(pretest_left_cond==T ~ paste0(ATT_cond, "^{+}"),
                                              pretest_right_cond==T ~ paste0(ATT_cond, "^{-}"),
                                              .default = ATT),
                      Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]"),
                      Conf_cond = paste0("[",str_trim(lower_cond),"; ",str_trim(upper_cond),"]"))

results_6 <- results[c("Estimate", "ATT", "Conf", "ATT_cond", "Conf_cond")]

results_6
```

```{r include=FALSE, warning=FALSE}

# combine all results 

results_final <- results_6[, c("Estimate", "ATT_cond")] %>% 
                               merge(results_1[, c("Estimate", "ATT_cond")], by.x = "Estimate", by.y = "Estimate", all = T) %>%
                               merge(results_2[, c("Estimate", "ATT_cond")], by.x = "Estimate", by.y = "Estimate", all = T) %>%
                               merge(results_5[, c("Estimate", "ATT_cond")], by.x = "Estimate", by.y = "Estimate", all = T) %>%
                               merge(results_3[, c("Estimate", "ATT_cond")], by.x = "Estimate", by.y = "Estimate", all = T) %>%
                               merge(results_4[, c("Estimate", "ATT_cond")], by.x = "Estimate", by.y = "Estimate", all = T)

# change column names and item order
colnames(results_final) <- c("Estimate", "To_World", "From_World", "To_Inter", "From_Inter", "To_Intra", "From_Intra")
results_final <- results_final[c(16, 3, 19, 4, 5, 18, 6, 9, 11, 13, 14, 17, 8, 10, 2, 12, 15, 7, 1),]  

## create Latex output ##
results_final <- rbind(results_final[1,],c("by group", rep("", ncol(results_final)-1)) ,results_final[2:nrow(results_final),])


# Insert multirow cell into the appropriate position in the LaTeX code
addtorow <- list()
addtorow$pos <- list(nrow(results_final),1)
addtorow$command <- c("[2ex] \\hline \\hline", 
                      "[1ex]")

# Modify the LaTeX code
latex_code <- print.xtable(xtable(results_final, caption = "Direction-specific analysis of group time treatment effects"),
                           label = "tab:did_reshuffling",
                           caption.placement = "top",
                           include.rownames = FALSE,
                           add.to.row = addtorow,
                           hline.after = c(-1,-1,0, 2),
                           size = "\\begin{adjustbox}{max width=\\textwidth}")

latex_code <- gsub("Estimate & To\\\\_World & From\\\\_World & To\\\\_Inter & From\\\\_Inter & To\\\\_Intra & From\\\\_Intra","Control group: & \\\\multicolumn{6}{c}{Not yet treated} \\\\\\\\\n \\\\cmidrule(lr){2-7} PTA(Cond.) & To \\\\emph{World} & From \\\\emph{World} & To \\\\emph{Inter} & From \\\\emph{Inter} & To \\\\emph{Intra} & From \\\\emph{Intra} ", latex_code)

latex_code <- gsub("\\\\end\\{tabular\\}", "\\\\end{tabular} \n \\\\end{adjustbox} \\\\label{tab:did_reshuffling}
\\\\begin{minipage}{15cm} \\\\\\\\
\\\\footnotesize Note: Stars indicate that the uniform confidence interval does not include zero. \\\\Superscripts + and - indicates that we can reject the null of equal average pseudo treatment effects between treated and untreated,\\\\ while superscript + indicates that the treatment effect is biased downward and \\\\superscript - indicates that the treatment effect is biased upward. \\\\textit{World} refers to container shipments to or from ports in other world regions. \\\\textit{Inter} refers to interregional shipments that is to or from ports in the other European region. \\\\textit{Intra} refers to intraregional shipments that is to or from ports in the same European region. Partial missing ATT estimates for the ports of Amsterdam, Moerdijk, Gdynia, and Dunkerque are due to missing reports on container shipments for the respective direction and region pair in the period of treatment and/or the period before. \\\\\\\\
\\\\end{minipage}", latex_code)


latex_code <- gsub("by group", "\\\\emph{by group}", latex_code)
latex_code <- gsub("lllllll", "lcccccc", latex_code)
latex_code <- gsub("\\\\verb\\|\\^\\|\\\\\\{\\+\\\\\\}", "\\\\textsuperscript{+}", latex_code)
latex_code <- gsub("\\\\verb\\|\\^\\|\\\\\\{-\\\\\\}", "\\\\textsuperscript{-}", latex_code)

# Save modified LaTeX code to a .tex file
cat(latex_code, file = file.path(getwd(), "results_tables", "did_reshuffling.tex"))


  
```

