---
title: "Reshuffling_Subanaylses"
author: "Katja Kalkschmied"
date: "2024-04-18"
output: html_document
---

<!-- Prepare outflow dataset-->

```{r include=FALSE}
library(dplyr)
library(writexl)
library(readxl)
library(ggplot2)
library(echoice2)
library(doBy)
library(zoo)
library(fixest)
library(did)
library(gt)
library(CInf)

load("port_data_TEU_out.RData")

port_data_TEU_out <- filter(port_data_TEU_out, aggregate==0,
                        stat_port==1,              #filter out non-stat ports (and geographic aggregates)
                        TEU_yrly >=10000,          #filter out small ports
                        port_code!="NLRTM") %>%    #exclude Hamburg due to very recent treatment
  mutate(s_china = ifelse(sender_code=="CN_X_HK" | sender_code=="HK", 1, 0)) %>%
  group_by(port_code, sender_code) %>%
  mutate(pair_id=cur_group_id()) %>% ungroup() %>%
  rename(container=total_TEU) %>%
  rename(partner_code=sender_code) %>%
  rename(partner=sender)

listpartner <- port_data_TEU_out %>%
  group_by(partner_code) %>%
  slice(1) %>%
  ungroup() %>%
  select(partner_code, partner)


listreporter <- port_data_TEU_out %>%
  group_by(reporter_code) %>%
  slice(1) %>%
  ungroup() %>%
  select(reporter_code, reporter)

partner_region <- read_xlsx("partner_region.xlsx", sheet = "Sheet1")

reporter_region <- merge(listreporter, partner_region, by.x = "reporter_code", by.y = "partner_code", all.x = T) %>% 
  select(reporter_code, partner_region) %>% 
  rename("reporter_region" = "partner_region")

port_data_TEU_out <- merge(port_data_TEU_out,partner_region, by.x = "partner_code", by.y = "partner_code", all.x = T) %>%
  relocate(partner_region, .after = partner_code) %>%
  rename(partner_region=partner_region)
  
port_data_TEU_out <- merge(port_data_TEU_out,reporter_region, by = "reporter_code", all.x = T) %>%
  relocate(reporter_region, .after = reporter_code) 

port_data_TEU_out$NENE_region <- ifelse(port_data_TEU_out$reporter_region == 'NE' & port_data_TEU_out$partner_region == 'NE', 1, 0)
sum(port_data_TEU_out$NENE_region)

port_data_TEU_out$SESE_region <- ifelse(port_data_TEU_out$reporter_region == 'SE' & port_data_TEU_out$partner_region == 'SE', 1, 0)
sum(port_data_TEU_out$SESE_region)

port_data_TEU_out$NESE_region <- ifelse(port_data_TEU_out$reporter_region == 'NE' & port_data_TEU_out$partner_region == 'SE', 1, 0)
sum(port_data_TEU_out$NESE_region)

port_data_TEU_out$SENE_region <- ifelse(port_data_TEU_out$reporter_region == 'SE' & port_data_TEU_out$partner_region == 'NE', 1, 0)
sum(port_data_TEU_out$SENE_region)

port_data_TEU_out$NEEX_region <- ifelse(port_data_TEU_out$reporter_region == 'NE' & port_data_TEU_out$partner_region == 'EX', 1, 0)
sum(port_data_TEU_out$NEEX_region)

port_data_TEU_out$SEEX_region <- ifelse(port_data_TEU_out$reporter_region == 'SE' & port_data_TEU_out$partner_region == 'EX', 1, 0)
sum(port_data_TEU_out$SEEX_region)

region_pair <- ec_undummy(port_data_TEU_out, c('NENE_region', 'SESE_region', 'NESE_region', 'SENE_region','NEEX_region','SEEX_region'), "region_pair", ref_level = "What") %>%
  select(port_code, partner_code, region_pair, year, quarter) 

port_data_TEU_out <- merge(port_data_TEU_out,region_pair, by.x=c("port_code", "partner_code", "year", "quarter"), by.y=c("port_code", "partner_code", "year", "quarter"))


port_data_agg_out <- port_data_TEU_out %>% mutate(origin_china = ifelse(!is.na(container) & (partner_code=="CN_X_HK" | partner_code=="HK"),container,0)) %>%
  group_by(port, port_code, period, reporter_code) %>% 
  summarize(container = sum(container, na.rm=T),
            real_gdp_reporter = mean(real_gdp_reporter),
            origin_china = sum(origin_china),
            group = max(group),
            group_operation = max(group_operation),
            ownership_china = max(ownership_china),
            operation = max(operation)) %>% ungroup() %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container = mean(container, na.rm=T)) %>% ungroup()

port_list <- port_data_agg_out %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))
         
port_group_list_out <- port_data_agg_out %>% filter(group!=0) %>% group_by(group) %>%
  summarize(ports = toString(unique(port)))

port_group_list_op_out <- port_data_agg_out %>% filter(group_operation!=0) %>% group_by(group_operation) %>%
                                     summarize(ports = toString(unique(port))) %>% 
                                     rename(group = group_operation)
port_group_list_out <- rbind(port_group_list_out, port_group_list_op_out)
port_group_list_out <- port_group_list_out[!duplicated(port_group_list_out$group),]
port_group_list_out$ports <- paste(port_group_list_out$ports,paste("(", port_group_list_out$group, ")", sep = ""))
```


<!-- Add control variables-->

```{r include=FALSE}
# add terminal data to the data set
terminal_data <- read_xlsx("port_manual_berth.xlsx")

# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data.csv")

# control variables
control_var <- merge(wpi_data, terminal_data, by.x="port_code",by.y="port_code", all = T) %>%
               select(port_code, cont_berths, ships, cranes_fixed, cranes_mobile, cranes_floating, max_lift, cargo_depth)


# merge with data
port_data_TEU_out <- merge(port_data_TEU_out, control_var, by.x = c("port_code"), by.y = c("port_code"), all.x = T) 

port_data_TEU_out$cont_berths[port_data_TEU_out$cont_berths==0] <- 1
port_data_TEU_out$ships[port_data_TEU_out$ships==0] <- 1

### Control variables for DID ####

controls <- c("ships", "max_lift", "cargo_depth")
var_controls <- c("mean_container")
```


<!-- Estimate South-South outflows: NEW ESTIMATOR -->

```{r include=F, message=FALSE, warning=FALSE}

port_data_TEU_out_SESE <- port_data_TEU_out %>% 
  filter(region_pair=="SESE_region") %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id())


#### Estimation ot ATT with never treated as control group ####
attgt <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              #xformula = c("ships"),
                              #varformula = c("ships"),
                              #control_group = "not_yet_treated",
                              data = port_data_TEU_out_SESE)


attgt_cond <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              #control_group = "not_yet_treated",
                              data = port_data_TEU_out_SESE)



# putting together the results

results <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt$average_treatment_effect$att,
                                   attgt$groupwise_treatment_effects$att),
                       lower = c(attgt$average_treatment_effect$att - attgt$average_treatment_effect$crit_val,
                                attgt$groupwise_treatment_effects$att - attgt$groupwise_treatment_effects$crit_val),
                       upper = c(attgt$average_treatment_effect$att + attgt$average_treatment_effect$crit_val,
                                  attgt$groupwise_treatment_effects$att + attgt$groupwise_treatment_effects$crit_val),
                       ATT_cond = c(attgt_cond$average_treatment_effect$att,
                                   attgt_cond$groupwise_treatment_effects$att),
                       lower_cond = c(attgt_cond$average_treatment_effect$att - attgt_cond$average_treatment_effect$crit_val,
                                attgt_cond$groupwise_treatment_effects$att - attgt_cond$groupwise_treatment_effects$crit_val),
                       upper_cond = c(attgt_cond$average_treatment_effect$att + attgt_cond$average_treatment_effect$crit_val,
                                  attgt_cond$groupwise_treatment_effects$att + attgt_cond$groupwise_treatment_effects$crit_val)) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      sig_cond = (ATT_cond>0 & lower_cond>0) | (ATT_cond<0 & upper_cond<0),
                      across(c("ATT","ATT_cond","lower","upper","lower_cond","upper_cond"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT_cond = ifelse(sig_cond==T, paste0(ATT_cond, "*"), ATT_cond),
                      Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]"),
                      Conf_cond = paste0("[",str_trim(lower_cond),"; ",str_trim(upper_cond),"]"))
results <- results[c("Estimate", "ATT", "Conf", "ATT_cond", "Conf_cond")]

results
```

<!-- Estimate South-South outflows: OLD ESTIMATOR -->

```{r echo=FALSE, warning=FALSE, message=FALSE}
# from S to S (N=31,466)
port_data_TEU_out_SESE <- port_data_TEU_out %>% 
  filter(region_pair=="SESE_region") %>%
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id())


attgt_share <- att_gt(yname = "container",            #outcome variable
                      tname = "period",                 #time variable
                      idname = "port_id",                    #id for units (should be port_code*partner)
                      gname = "group",                    #grouping variable for first treatment. Is zero for never treated units
                      #xformla = ~X,                  #for potential covariates
                      #control_group="notyettreated",  #use not yet treated units as control group in addition to never treated units
                      allow_unbalanced_panel = TRUE,  #allows he use of unbalanced panel data. Increases computation time.
                      #est_method = "reg",             #indicates which estimation method should be used ("ipw", inverse probability weighting or "reg" for regression)
                      data = port_data_TEU_out_SESE)

# attgt_share_cond <- att_gt(yname = "share_china",            #outcome variable
#                 tname = "period",                 #time variable
#                 idname = "port_id",                    #id for units (should be port_code*partner)
#                 gname = "group",                    #grouping variable for first treatment. Is zero for never treated units
#                 xformla = ~mean_container+real_gdp_reporter,                  #for potential covariates
#                 #control_group="notyettreated",  #use not yet treated units as control group in addition to never treated units
#                 allow_unbalanced_panel = TRUE,  #allows he use of unbalanced panel data. Increases computation time.
#                 est_method = "reg",             #indicates which estimation method should be used ("ipw", inverse probability weighting or "reg" for regression)
#                 data = port_data_agg)


# option 1: simple weighted average treatment effect with weights proportional to the group size
agg_simple_share <- aggte(attgt_share, type = "simple", na.rm=T)
#agg_simple_share_cond <- aggte(attgt_share_cond, type = "simple", na.rm=T)

# option 2: event-study type aggregation by time under treatment
agg_es_share <- aggte(attgt_share, type = "dynamic", na.rm=T)
#agg_es_share_cond <- aggte(attgt_share_cond, type = "dynamic", na.rm=T)

# option 3: groupwise treatment effects
agg_gs_share <- aggte(attgt_share, type = "group", na.rm=T)
#agg_gs_share_cond <- aggte(attgt_share_cond, type = "group", na.rm=T)


#port_group_list$ports[match(as.character(agg_gs_op_share$egt), port_group_list$group)]
# putting together the results
share_results <- data.frame(Estimate = c("simple average", port_group_list_out$ports[match(as.character(agg_gs_share$egt), port_group_list_out$group)]),
                             ATT = c(agg_simple_share$overall.att,
                                     agg_gs_share$att.egt),
                             lower = c(agg_simple_share$overall.att-(agg_simple_share$overall.se*1.95), agg_gs_share$att.egt-(agg_gs_share$se.egt*agg_gs_share$crit.val.egt)),
                             upper = c(agg_simple_share$overall.att+(agg_simple_share$overall.se*1.95), agg_gs_share$att.egt+(agg_gs_share$se.egt*agg_gs_share$crit.val.egt)))

# share_results2 <- data.frame(Estimate = c("simple average", port_group_list$ports[match(as.character(agg_gs_op_share$egt), port_group_list$group)]),
#                        ATT = c(agg_simple_op_share$overall.att,
#                                    agg_gs_op_share$att.egt),
#                       lower = c(agg_simple_op_share$overall.att-(agg_simple_op_share$overall.se*1.95), agg_gs_op_share$att.egt-(agg_gs_op_share$se.egt*agg_gs_op_share$crit.val.egt)),
#                       upper = c(agg_simple_op_share$overall.att+(agg_simple_op_share$overall.se*1.95), agg_gs_op_share$att.egt+(agg_gs_op_share$se.egt*agg_gs_op_share$crit.val.egt)))
# share_results <- merge(share_results1, share_results2, by.x = "Estimate", by.y = "Estimate", all =  T)
#share_results <- share_results[c(12, 1:11),]

# generating a gt table
share_results_gt <- gt(share_results, rowname_col = "Estimate") |>
              tab_header(
                title = "Aggregation of group time average treatment effects",
                subtitle = "Control group: Never treated") |>
              cols_label(
                lower="[95%",
                upper="conf.int.]"
                # ATT.x="ATT",
                # lower.x="[95%",
                # upper.x="conf.int.]",
                # ATT.y="ATT",
                # lower.y="[95%",
                # upper.y="conf.int.]"
              ) |>
              tab_spanner(label = "uncond. PTA",
                          columns = c("ATT", "lower", "upper")) |>
              # tab_spanner(label = "uncond. PTA",
              #             columns = c("ATT.x", "lower.x", "upper.x")) |>
              # tab_spanner(label = "Chinese operation",
              #             columns = c("ATT.y", "lower.y", "upper.y")) |>
              tab_row_group(label = "by group:",
                            rows = contains("(")) |>
              row_group_order(groups = c(NA,"by group:")) |>
              sub_missing(columns = everything(),
                          rows = everything(),
                          missing_text = "") |>
              tab_footnote(footnote = "Confidence interval does not include zero.",
                           location = list(
                                            cells_body(columns=c(ATT),
                                                 rows = lower > 0 | upper < 0)
                                            # cells_body(columns=c(ATT.x),
                                            #      rows = lower.x > 0 | upper.x < 0),
                                            # cells_body(columns=c(ATT.y),
                                            #      rows = lower.y > 0 | upper.y < 0)
                                           ),
                           placement = "right") |>
              tab_footnote(footnote = "First treatment period in brackets.") |>
              opt_footnote_marks(marks = "standard") |>
              fmt_number(decimals = 2)

share_results_gt

```