---
title: "Robustness Checks"
author: "Paul Stricker"
bibliography: literature_list.bib
date: "2024-01-22"
output: 
 html_document:
      keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r include=FALSE, warning=FALSE}
library(dplyr)
library(tidyr)
library(patchwork)
library(ggplot2)
library(fixest)
library(did)
library(CInf)
library(gt)
library(readxl)
library(stringr)
library(cowplot)
library(xtable)
library(extrafont)

loadfonts(device = "win")
set.seed(100)

#load data
load("port_data_TEU_110.RData")

sample <- c("BEANR", "BEGNE", "BEZEE", "BGVAR", "CYLMS", "DEBRV", "DECUX", "DELBC", "DEHAM", "DEWVN", "DKAAL", "DKAAR", "DKCPH", "DKEBJ", "DKFRC", "EETLL", "ESAGP", "ESALC", "ESALG", "ESBCN", "ESBIO", "ESCAD", "ESCAR", "ESCAS", "ESGIJ",  "ESLPA", "ESMLN", "ESMPG", "ESPMI", "ESSCT", "ESSDR", "ESSVQ", "ESTAR", "ESVGO", "ESVIL", "ESVLC", "FIHEL", "FIHKO", "FIOUL", "FIPOR", "FIRAU", "FRBES", "FRDKK", "FRLEH", "FRMRS", "FRNTE", "GBBEL", "GBBRS", "GBCDF", "GBFOR", "GBFXT", "GBGOO", "GBHUL", "GBIMM", "GBLIV", "GBLON", "GBMED", "GBMME", "GBPME", "GBSOU", "GBWPT", "GRPIR", "GRSKG", "HRPLE", "HRRJK", "IEDRO", "IEDUB", "IEORK", "IEWAT", "ITAOI", "ITBRI", "ITCAG", "ITCTA", "ITCVV", "ITGIT", "ITGOA", "ITLIV", "ITMDC", "ITNAP", "ITRAN", "ITSAL", "ITSPE", "ITSVN", "ITTAR", "ITTRS", "ITVCE", "LTKLJ", "LVRIX", "MEBAR", "MTMAR", "NLAMS", "NLMOE", "NLRTM", "NOKRS", "NOMJF", "NOMSS", "NOOSL", "PLGDN", "PLGDY", "PLSZZ", "PTCNL", "PTFNC", "PTLEI", "PTLIS", "PTPDL", "PTPRV", "PTSET", "PTSIE", "ROCND", "SEGOT", "SEGVX", "SEHAD", "SEHEL", "SEMMA", "SENRK", "SESOE", "SEVST", "SIKOP", "TRAMB", "TRAYT", "TRGEM", "TRISK", "TRIZM", "TRIZT", "TRMER", "TRSSX", "TRTEK")


port_data_TEU <- filter(port_data_TEU, aggregate==0,
                                       stat_port==1,              #filter out non-stat ports (and geographic aggregates)
                                       TEU_yrly >=20000,      #filter out small ports
                                       port_code %in% sample,
                                        period<=105) %>%        
             mutate(s_china = ifelse(sender_code=="CN_X_HK" | sender_code=="HK", 1, 0),
                     port = ifelse(port=="Antwerpen", "Antwerp", port)) %>%
             group_by(port_code, sender_code) %>%
             mutate(pair_id=cur_group_id()) %>% ungroup() %>%
             rename(container=total_TEU)

port_data_agg <- port_data_TEU %>% mutate(origin_china = ifelse(!is.na(container) & (sender_code=="CN_X_HK" | sender_code=="HK"),container,0)) %>%
                               group_by(port, port_code, period, reporter_code, year, quarter) %>% 
                               summarize(container = sum(container, na.rm=T),
                                         real_gdp_reporter = mean(real_gdp_reporter),
                                         origin_china = sum(origin_china),
                                         group = max(group),
                                         group_operation = max(group_operation),
                                         ownership_china = max(ownership_china),
                                         operation = max(operation)) %>% ungroup() %>%
                              group_by(port_code) %>% 
                              mutate(port_id = cur_group_id(),
                                     mean_container = mean(container, na.rm=T)) %>% ungroup()

port_data_agg_ny <- port_data_agg %>% filter(group!=0)

port_group_list <- port_data_agg %>% filter(group!=0) %>% group_by(group) %>%
                                     summarize(ports = toString(unique(port)))
port_group_list_op <- port_data_agg %>% filter(group_operation!=0) %>% group_by(group_operation) %>%
                                     summarize(ports = toString(unique(port))) %>% 
                                     rename(group = group_operation)
port_group_list <- rbind(port_group_list, port_group_list_op)
port_group_list <- port_group_list[!duplicated(port_group_list$group),]
port_group_list$ports <- paste(port_group_list$ports,paste("(", port_group_list$group, ")", sep = ""))

port_list <- port_data_agg %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))


#exclude Rotterdam and Hamburg's treated values
port_data_TEU$container[port_data_TEU$port_code=="NLRTM" & between(port_data_TEU$year,2011,2020)]<-NA
port_data_agg$container[port_data_agg$port_code=="NLRTM" & between(port_data_agg$year,2011,2020)]<-NA


# add Cosco and Terminal data to the data set
terminal_data <- read_xlsx("terminal_throughput.xlsx")


# add control variables
load("berth_data.RData")
wpi_data <- read.csv("WPI_data2.csv")
markets <- read.csv(file.path(getwd(),"control variables_new", "markets.csv"))
TENtec <- read.csv(file.path(getwd(),"control variables_new", "TENtec_corridors.csv")) 



terminal_data <- merge(port_data_agg, terminal_data, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) %>%
                 merge(berth_data, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) %>%
                 merge(wpi_data, by.x = c("port_code", "year"), by.y = c("port_code", "year"), all.x = T) %>%
                 merge(markets[,c("port_code", "year", "local_markets", "foreign_markets", "all_markets")],
                       by.x=c("port_code", "year"), by.y = c("port_code", "year"), all.x=T) %>% 
                 arrange(port_code, desc(period)) %>% group_by(port_code) %>% 
                 fill(c("local_markets", "local_markets", "foreign_markets", "all_markets", "cargo_depth"), .direction = "downup") %>%  
                 merge(TENtec[,c("port_code", "node.score", "TENtec.core.port")], by.x=c("port_code"), by.y = c("port_code"), all.x=T) %>%
                 mutate(port_code = case_when(port_code=="BEZEE" | port_code=="BEANR" ~ "BE003",
                                              port_code=="ESVLC" ~ "ESBIO",
                                              .default = port_code),
                        port = case_when(port_code=="BE003" ~ "Zeebrugge and Antwerp",
                                         port_code=="ESBIO" ~ "Valencia and Bilbao",
                                         .default = port.x),) %>% 
                 group_by(port_code, port, year, quarter, period) %>%
                 summarize(across(c(terminal_TEU, container,quay_length, cosco_length), ~sum(., na.rm=T), .names = "{.col}"),
                           across(c(local_markets, foreign_markets, node.score, cargo_depth, group), ~max(.,na.rm=T), .names="{.col}")) %>%
                 mutate(terminal_TEU = ifelse(terminal_TEU==0, NA, terminal_TEU),
                        across(starts_with("cosco_") , ~ifelse(is.na(terminal_TEU), NA, .x))) %>%
                 group_by(port_code) %>%
                 mutate(treated=(sum(!is.na(terminal_TEU))>0),
                        terminal_TEU = terminal_TEU*1000,
                        change=container - lag(container),) %>% ungroup()


#exclude Rotterdam and Antwerp when data is unavailable
terminal_data$container[terminal_data$port_code=="NLRTM" & between(terminal_data$year,2011,2020)]<-NA
terminal_data <- terminal_data[!(terminal_data$port_code=="BE003" & terminal_data$year >=2022),]

#set graph theme
theme_set(theme_minimal() + theme(legend.position = 'none'))

### Control variables for DID ####
terminal_data$quay_length[terminal_data$quay_length==0] <- 100


### Control variables for DID ####


controls <-  c("quay_length", "local_markets", "foreign_markets", "node.score", "cargo_depth")
var_controls <- c("quay_length")


```


# Cosco terminal level robustness check

## Terminal-level graph



```{r include=FALSE, warning=FALSE, message=FALSE}


graph_list <- list()
for (i in seq_along(unique(terminal_data$port_code[terminal_data$treated==1]))) {
  port_c <- unique(terminal_data$port_code[terminal_data$treated==1])[i]
  port_name <- terminal_data$port[match(port_c, terminal_data$port_code)]



graph_list[[i]] <- terminal_data %>% mutate(residual = ifelse(!is.na(terminal_TEU) & container!=0, container-terminal_TEU, container),
                                            residual = ifelse(is.na(residual),0,residual)) %>% 
                          pivot_longer(c("terminal_TEU", "residual"), names_to = "type", values_to = "throughput") %>% 
                          filter(port_code==port_c) %>%
                          ggplot(aes(x=period, y=throughput/1000, fill=type)) + 
                          geom_area() +
                          scale_y_continuous(
                            name="throughput") +
                          scale_fill_manual(values=c("grey50", "grey30"),
                                            labels=c( "total port", "cosco terminal")) +
                          labs(title=port_name) +
                          theme_minimal() +
                          theme(panel.background = element_blank(),
                                strip.text = element_text(hjust = 0, size=12),
                                text = element_text(size=10, family="LM Roman 10"),
                                #legend.position = "bottom",
                                legend.title = element_blank(),
                                axis.title.x = element_blank(),
                                axis.title.y = element_blank())
}
```

```{r include=TRUE, message=FALSE, echo=FALSE, warning=FALSE, fig.dim = c(6, 9),fig.align = 'center'}

x.title <- ggdraw() + geom_text(aes(label="TEU (thousands)", angle = 90), x = 0.5, y = 0.5, hjust = 0.5, vjust = 1, size = 5, family="LM Roman 10")
y.title <- ggdraw() + geom_text(aes(label="Period"), x = 0.5, y = 0.5, hjust = 0.5, vjust = 1, size = 5, family="LM Roman 10")

legend <- get_legend(graph_list[[1]] + guides(fill = guide_legend(direction = "horizontal")))

for (i in 1:6){
  graph_list[[i]] = graph_list[[i]] + theme(legend.position = "none")
}

plots1 <- plot_grid(plotlist = graph_list, ncol=2, align = "hv") 

plots1 <- plot_grid(plots1, y.title, legend, ncol=1, rel_heights = c(0.90,0.05, 0.05) ) 

plot_grid(x.title, plots1, ncol = 2, rel_widths = c(0.05,0.95))

print(plots1)
ggsave(width=10, height=11, filename = "rob.pdf", path = file.path(getwd(), "figures"))
  
```

## Terminal-level DiD

```{r include=FALSE, warning=FALSE, echo=FALSE}
set.seed(100)

# Construct the dataset for DiD 

#How many periods are allowed for adjustment process?
treatmentlag <- 1

robustness_cosco <- terminal_data %>% filter(!is.na(terminal_TEU)) %>% select(port_code, port, year, quarter, period, terminal_TEU, cosco_length, local_markets, foreign_markets, node.score, cargo_depth) %>% rename(quay_length=cosco_length, container=terminal_TEU) %>%
                 group_by(port_code) %>%
                 mutate(group=min(period)+1) %>% ungroup()


#control ports
control_ports <- terminal_data %>% filter(group==0 & !is.infinite(cargo_depth))  

# putting it all together
robustness_cosco <- rbind(robustness_cosco, control_ports[, colnames(robustness_cosco)])%>% group_by(port_code) %>%
                    mutate(port_id=cur_group_id())



port_group_list_rob <- robustness_cosco %>% filter(group!=0) %>% group_by(group) %>%
                                     summarize(ports = toString(unique(port)),
                                               id = mean(port_id))


attgt_rob <- simple_staggered_did(yname = "container",            #outcome variable
                tname = "period",                 #time variable
                idname = "port_id",                    #id for units (should be port_code*sender)
                gname = "group",                    #grouping variable for first treatment. Is zero for never treated units
                xformula = controls,
                varformula = var_controls,
                data = robustness_cosco)

#making a table
results <- data.frame(Estimate = c("simple average", port_group_list_rob$ports[match(as.character(attgt_rob$groupwise_treatment_effects$id), port_group_list_rob$id)]),
                       ATT = c(attgt_rob$average_treatment_effect$att,
                                   attgt_rob$groupwise_treatment_effects$att),
                       lower = c(attgt_rob$average_treatment_effect$att - attgt_rob$average_treatment_effect$crit_val,
                                attgt_rob$groupwise_treatment_effects$att - attgt_rob$groupwise_treatment_effects$crit_val),
                       upper = c(attgt_rob$average_treatment_effect$att + attgt_rob$average_treatment_effect$crit_val,
                                  attgt_rob$groupwise_treatment_effects$att + attgt_rob$groupwise_treatment_effects$crit_val)) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      across(c("ATT","lower","upper"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      Conf = paste0("[",str_trim(lower),"; ",str_trim(upper),"]"))

results <- results[c("Estimate", "ATT", "Conf")]

# make a gt table
results_gt_rob <- gt(results, rowname_col = "Estimate") |>
              tab_header(
                title = "Aggregation of group time average treatment effects",
                subtitle = "Control group: Never treated") |>
              cols_label(
                Conf="95% CI"
              ) |>
              tab_row_group(label = "by group:",
                            rows = c(2:7)) |>
              row_group_order(groups = c(NA,"by group:")) |>
              sub_missing(columns = everything(),
                          rows = everything(),
                          missing_text = "") |>
              tab_footnote(footnote = "Confidence intervals are based on bootstrapped errors.")


#generate Latex table
#add group row
results<- rbind(results[1,],c("by group", rep("", ncol(results)-1)) ,results[2:7,]) 


# Insert multirow cell into the appropriate position in the LaTeX code
addtorow <- list()
addtorow$pos <- list(nrow(results),1)
addtorow$command <- c("[2ex] \\hline \\hline \\multicolumn{3}{l}{\\shortstack[l]{Note: Stars indicate that the uniform confidence interval \\\\does not include zero.\\\\}}", 
                      "[1ex]")

# Modify the LaTeX code
latex_code <- print.xtable(xtable(results, caption = "Cosco terminal treatment effects"),
                           label = "tab:cosco_results",
                           caption.placement = "top",
                           include.rownames = FALSE,
                           add.to.row = addtorow,
                           hline.after = c(-1,-1,0, 2),
                           size = "\\begin{adjustbox}{max width=\\textwidth}")

latex_code <- gsub("Estimate & ATT & Conf"," & ATT & 95\\\\% CI ", latex_code)

latex_code <- gsub("\\\\end\\{tabular\\}", "\\\\end{tabular} \n \\\\end{adjustbox} \\\\label{tab:cosco_results}", latex_code)
latex_code <- gsub("by group", "\\\\emph{by group}", latex_code)
latex_code <- gsub("lll", "lcc", latex_code)

# Save modified LaTeX code to a .tex file
cat(latex_code, file = file.path(getwd(), "results_tables", "cosco_results.tex"))

```


```{r include=TRUE, echo=FALSE}
results_gt_rob

```


## The role of Chinese Containers


```{r include=F, warning=FALSE}
set.seed(100)

#### DiD without China ###
port_data_agg_woCHN <- port_data_TEU %>% mutate(origin_china = ifelse(!is.na(container) & (sender_code=="CN_X_HK" | sender_code=="HK"),container,0)) %>%
                                         filter(origin_china==0) %>%
                               group_by(port, port_code, period, reporter_code, year, quarter) %>% 
                               summarize(container = sum(container, na.rm=T),
                                         group = max(group)) %>% ungroup() %>%
                              group_by(port_code) %>% 
                              mutate(port_id = cur_group_id()) %>% ungroup() %>%
                               merge(berth_data, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) %>%
                 merge(wpi_data, by.x = c("port_code", "year"), by.y = c("port_code", "year"), all.x = T) %>%
                 merge(markets[,c("port_code", "year", "local_markets", "foreign_markets", "all_markets")],
                       by.x=c("port_code", "year"), by.y = c("port_code", "year"), all.x=T) %>% 
                 arrange(port_code, desc(period)) %>% group_by(port_code) %>% 
                 fill(c("local_markets", "local_markets", "foreign_markets", "all_markets", "cargo_depth"), .direction = "downup") %>%  
                 merge(TENtec[,c("port_code", "node.score", "TENtec.core.port")], by.x=c("port_code"), by.y = c("port_code"), all.x=T)


#exclude Rotterdam 
port_data_agg_woCHN$container[port_data_agg_woCHN$port_code=="NLRTM" & between(port_data_agg_woCHN$year,2011,2020)]<-NA

port_data_agg_woCHN$quay_length[port_data_agg_woCHN$quay_length==0] <- 100
port_data_agg_woCHN$cranes[port_data_agg_woCHN$cranes==0] <- 1


attgt_woCHN <- simple_staggered_did(yname = "container",            #outcome variable
                tname = "period",                 #time variable
                idname = "port_id",                    #id for units (should be port_code*sender)
                gname = "group",                    #grouping variable for first treatment. Is zero for never treated units
                xformula = controls,
                varformula = var_controls,
                control_group = "not_yet_treated",
                data = port_data_agg_woCHN)

# results table
results <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_woCHN$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt_woCHN$average_treatment_effect$att,
                                   attgt_woCHN$groupwise_treatment_effects$att),
                       lower = c(attgt_woCHN$average_treatment_effect$att - attgt_woCHN$average_treatment_effect$crit_val,
                                attgt_woCHN$groupwise_treatment_effects$att - attgt_woCHN$groupwise_treatment_effects$crit_val),
                       upper = c(attgt_woCHN$average_treatment_effect$att + attgt_woCHN$average_treatment_effect$crit_val,
                                  attgt_woCHN$groupwise_treatment_effects$att + attgt_woCHN$groupwise_treatment_effects$crit_val),
                      p_value_left = c(NA, attgt_woCHN$groupwise_treatment_effects$pre_treatment_p_value_left)) %>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                              pretest_left = (p_value_left < 0.05) & !is.na(p_value_left),
                              pretest_right = (p_value_left > 0.95) & !is.na(p_value_left),
                              across(c("ATT","lower","upper"), ~ format(round(.,digits=0), big.mark = ",")),
                              ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                              ATT = case_when(pretest_left==T ~ paste0(ATT, "^{+}"),
                                              pretest_right==T ~ paste0(ATT, "^{-}"),
                                              .default = ATT),
                              Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]")) %>%
                              select(Estimate, ATT, Conf)

results <- results[c("Estimate", "ATT", "Conf")]


#### DiD with china share ####
port_data_agg <- mutate(port_data_agg, share_china=origin_china/(container)) 

attgt_share <- simple_staggered_did(yname = "share_china",            #outcome variable
                tname = "period",                 #time variable
                idname = "port_id",                    #id for units (should be port_code*sender)
                gname = "group",                    #grouping variable for first treatment. Is zero for never treated units
                data = port_data_agg)

# results table
results_share <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_share$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt_share$average_treatment_effect$att,
                                   attgt_share$groupwise_treatment_effects$att),
                       lower = c(attgt_share$average_treatment_effect$att - attgt_share$average_treatment_effect$crit_val,
                                attgt_share$groupwise_treatment_effects$att - attgt_share$groupwise_treatment_effects$crit_val),
                       upper = c(attgt_share$average_treatment_effect$att + attgt_share$average_treatment_effect$crit_val,
                                  attgt_share$groupwise_treatment_effects$att + attgt_share$groupwise_treatment_effects$crit_val),
                       p_value_left = c(NA, attgt_share$groupwise_treatment_effects$pre_treatment_p_value_left)) %>%
                mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                              pretest_left = (p_value_left < 0.05) & !is.na(p_value_left),
                              pretest_right = (p_value_left > 0.95) & !is.na(p_value_left),
                              across(c("ATT","lower","upper"), ~ format(round(.,digits=4), big.mark = ",")),
                              ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                              ATT = case_when(pretest_left==T ~ paste0(ATT, "^{+}"),
                                              pretest_right==T ~ paste0(ATT, "^{-}"),
                                              .default = ATT),
                              Conf = paste0("[",str_trim(lower),", ",str_trim(upper),"]")) %>%
                              select(Estimate, ATT, Conf)

results_share <- results_share[c("Estimate", "ATT", "Conf")]

# combining results
results_final <- cbind(results, results_share[,c(2,3)]) 
colnames(results_final)[c(4,5)] <- c("ATT1","Conf1")



# putting together the results
results_gt_woCHN <- gt(results_final, rowname_col = "Estimate") |>
              tab_header(
                title = "Aggregated average treatment effects on container throughput from different origins",
                subtitle = "Control group: Never treated") |>
              cols_label(
                ATT="TEU without China",
                ATT1="Share of chinese TEU",
                Conf="95% CI",
                Conf1="95% CI") |>
              tab_stubhead(label = "Dependent variable:")|>
              tab_row_group(label = "by group:",
                            rows = c(2:19)) |>
              row_group_order(groups = c(NA,"by group:")) |>
              sub_missing(columns = everything(),
                          rows = everything(),
                          missing_text = "") |>
              tab_footnote(footnote = "Confidence intervals are based on bootstrapped errors. ")


#generate Latex table
#add group row
results_final <- rbind(results_final[1,],c("by group", rep("", ncol(results_final)-1)) ,results_final[2:19,]) 

# Insert multirow cell into the appropriate position in the LaTeX code
addtorow <- list()
addtorow$pos <- list(nrow(results_final),1)
addtorow$command <- c("[2ex] \\hline \\hline \\multicolumn{5}{l}{\\shortstack[l]{Note: Stars indicate that the uniform confidence interval does not include zero. \\\\ Superscript x indicates that we can reject the null of equal average pseudo \\\\ treatment effects between treated and untreated.}}", 
                      "[1ex]")

# Modify the LaTeX code
latex_code <- print.xtable(xtable(results_final, caption = "Aggregation of group time treatment effects without China"),
                           label = "tab:wochina_results",
                           caption.placement = "top",
                           include.rownames = FALSE,
                           add.to.row = addtorow,
                           hline.after = c(-1,-1,0, 2),
                           size = "\\begin{adjustbox}{max width=\\textwidth}")

latex_code <- gsub("Estimate & ATT & Conf & ATT1 & Conf1","Dependent var.: & \\\\multicolumn{2}{c}{TEU without China} & \\\\multicolumn{2}{c}{Share of Chinese TEU} \\\\\\\\\n \\\\cmidrule(lr){2-3} \\\\cmidrule(lr){4-5} PTA & Cond. & 95\\\\% CI & Uncond. & 95\\\\% CI" , latex_code)

latex_code <- gsub("\\\\end\\{tabular\\}", "\\\\end{tabular} \n \\\\end{adjustbox} \\\\label{tab:wochina_results}", latex_code)
latex_code <- gsub("by group", "\\\\emph{by group}", latex_code)
latex_code <- gsub("lllll", "lcccc", latex_code)
latex_code <- gsub("\\\\verb\\|\\^\\|\\\\\\{x\\\\\\}", "\\\\textsuperscript{x}", latex_code)

# Save modified LaTeX code to a .tex file
cat(latex_code, file = file.path(getwd(), "results_tables", "wochina_results.tex"))

```

```{r include =FALSE}
# table for presentation

results_presentation <- results_final[,c(1,2,4)]

# Insert multirow cell into the appropriate position in the LaTeX code
addtorow <- list()
addtorow$pos <- list(nrow(results_final),1)
addtorow$command <- c("[2ex] \\hline \\hline \\multicolumn{3}{l}{\\shortstack[l]{Note: Stars indicate that the uniform confidence interval does not include zero. \\\\ Superscript x indicates that we can reject the null of equal average pseudo \\\\ treatment effects between treated and untreated.}}", 
                      "[1ex]")

# Modify the LaTeX code
latex_code <- print.xtable(xtable(results_presentation),
                           label = "tab:wochina_results",
                           caption.placement = "top",
                           include.rownames = FALSE,
                           add.to.row = addtorow,
                           hline.after = c(-1,-1,0, 2),
                           size = "\\begin{adjustbox}{max width=\\textwidth}")

latex_code <- gsub("Estimate & ATT & ATT1","Dependent var.: & \\\\multicolumn{1}{c}{TEU without China} & \\\\multicolumn{1}{c}{Share of Chinese TEU} \\\\\\\\\n \\\\cmidrule(lr){2-2} \\\\cmidrule(lr){3-3} PTA & Cond. & Uncond." , latex_code)

latex_code <- gsub("\\\\end\\{tabular\\}", "\\\\end{tabular} \n \\\\end{adjustbox} \\\\label{tab:wochina_results}", latex_code)
latex_code <- gsub("by group", "\\\\emph{by group}", latex_code)
latex_code <- gsub("lll", "lcc", latex_code)
latex_code <- gsub("\\\\verb\\|\\^\\|\\\\\\{x\\\\\\}", "\\\\textsuperscript{x}", latex_code)

# Save modified LaTeX code to a .tex file
cat(latex_code, file = file.path(getwd(), "presentation_results", "wochina_results_presentation.tex"))


```


```{r include=T, echo=FALSE}

results_gt_woCHN
```

