---
title: "test"
author: "Paul Stricker"
bibliography: literature_list.bib
date: "2023-11-29"
output: 
 html_document:
      keep_md: true
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE, warning=FALSE, message=FALSE}
library(dplyr)
library(tidyr)
library(stringr)
library(patchwork)
library(ggplot2)
library(did)
#library(CInf)
library(readxl)
library(gt)
library(xtable)
library(extrafont)
library(writexl)
library(echoice2)
library(doBy)
library(zoo)
```


# Extensive Margins

```{r include=FALSE, warning=FALSE, message=FALSE}
loadfonts(device = "win")
set.seed(100)

#load data
load("port_data_TEU.RData")

port_data_TEU <- filter(port_data_TEU, aggregate==0,
                                       stat_port==1,              #filter out non-stat ports (and geographic aggregates)
                                       TEU_yrly >=20000,          #filter out small ports
                                       port_code!="DEHAM") %>%    #exclude Hamburg due to very recent treatment
             mutate(s_china = ifelse(sender_code=="CN_X_HK" | sender_code=="HK", 1, 0)) %>%
             group_by(port_code, sender_code) %>%
             mutate(pair_id=cur_group_id()) %>% ungroup() %>%
             rename(container=total_TEU)

port_data_TEU <- port_data_TEU %>%
  group_by(port_code, period) %>%
  mutate(partner_number = n_distinct(sender_code)) %>%
  ungroup()


port_data_agg <- port_data_TEU %>% mutate(origin_china = ifelse(!is.na(container) & (sender_code=="CN_X_HK" | sender_code=="HK"),container,0)) %>%
                               group_by(port, port_code, period, reporter_code) %>% 
                               summarize(container = sum(container, na.rm=T),
                                         real_gdp_reporter = mean(real_gdp_reporter),
                                         origin_china = sum(origin_china),
                                         group = max(group),
                                         group_operation = max(group_operation),
                                         ownership_china = max(ownership_china),
                                         operation = max(operation),
                                         year = max(year),
                                         quarter = max(quarter),
                                         partner_number = max(partner_number)) %>% ungroup() %>%
                              group_by(port_code) %>% 
                              mutate(port_id = cur_group_id(),
                                     mean_container = mean(container, na.rm=T)) %>% ungroup()

#exclude Rotterdam
port_data_TEU$container[port_data_TEU$port_code=="NLRTM" & between(port_data_TEU$year,2011,2020)]<-NA
port_data_agg$container[port_data_agg$port_code=="NLRTM" & between(port_data_agg$year,2011,2020)]<-NA

port_data_agg_ny <- port_data_agg %>% filter(group!=0)

port_list <- port_data_agg %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))

port_group_list <- port_data_agg %>% filter(group!=0) %>% group_by(group) %>%
                                     summarize(ports = toString(unique(port)))
port_group_list_op <- port_data_agg %>% filter(group_operation!=0) %>% group_by(group_operation) %>%
                                     summarize(ports = toString(unique(port))) %>% 
                                     rename(group = group_operation)
port_group_list <- rbind(port_group_list, port_group_list_op)
port_group_list <- port_group_list[!duplicated(port_group_list$group),]
port_group_list$ports <- paste(port_group_list$ports,paste("(", port_group_list$group, ")", sep = ""))

# Add Control variables --------------------------------------------------------

# add terminal data to the data set
#terminal_data <- read_xlsx("port_manual_berth.xlsx")

load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data.csv")

# control variables
control_var <- merge(wpi_data, terminal_data, by.x="port_code",by.y="port_code", all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      cranes_fixed, cranes_mobile, cranes_floating, max_lift, cargo_depth)


# merge with aggregated data
port_data_agg <- merge(port_data_agg, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 

#port_data_agg$ships[port_data_agg$ships==0] <- 1

port_data_agg$quay_length[port_data_agg$quay_length==0] <- 100
port_data_agg$cranes[port_data_agg$cranes==0] <- 1

### Control variables for DID ####


controls <- c("cranes", "max_lift", "cargo_depth")
var_controls <- c("quay_length")

```

```{r include=F, message=FALSE, warning=FALSE}

#### Estimate ATT with not-yet-treated control group ####

attgt_cond_ny <- simple_staggered_did(yname = "partner_number",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "port_id",                    #id for units (should be port_code*sender)
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_agg)



# putting together the results


results <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond_ny$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt_cond_ny$average_treatment_effect$att,
                                   attgt_cond_ny$groupwise_treatment_effects$att),
                       lower = c(attgt_cond_ny$average_treatment_effect$att - attgt_cond_ny$average_treatment_effect$crit_val,
                                attgt_cond_ny$groupwise_treatment_effects$att - attgt_cond_ny$groupwise_treatment_effects$crit_val),
                       upper = c(attgt_cond_ny$average_treatment_effect$att + attgt_cond_ny$average_treatment_effect$crit_val,
                                  attgt_cond_ny$groupwise_treatment_effects$att + attgt_cond_ny$groupwise_treatment_effects$crit_val),
                        p_value = c(NA, attgt_cond_ny$groupwise_treatment_effects$pre_treatment_p_value))%>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      pretest = (p_value < 0.05) & !is.na(p_value),
                      across(c("ATT","lower","upper"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = ifelse(pretest==T, paste0(ATT, "^{x}"),ATT),
                      Conf = paste0("[",str_trim(lower),"; ",str_trim(upper),"]"))

results <- results[c("Estimate", "ATT", "Conf")]

```


# Intensive Margins

```{r include=FALSE}

load("port_data_TEU.RData")

port_data_TEU <- filter(port_data_TEU, aggregate==0,
                        stat_port==1,              #filter out non-stat ports (and geographic aggregates)
                        TEU_yrly >=20000,          #filter out small ports
                        port_code!="DEHAM") %>%    
  mutate(s_china = ifelse(sender_code=="CN_X_HK" | sender_code=="HK", 1, 0)) %>%
  group_by(port_code, sender_code) %>%
  mutate(pair_id=cur_group_id()) %>% ungroup() %>%
  rename(container=total_TEU) %>%
  rename(partner_code=sender_code) %>%
  rename(partner=sender)

port_data_TEU$container[port_data_TEU$port_code=="NLRTM" & between(port_data_TEU$year,2011,2020)]<-NA


listpartner <- port_data_TEU %>%
  group_by(partner_code) %>%
  slice(1) %>%
  ungroup() %>%
  select(partner_code, partner)


listreporter <- port_data_TEU %>%
  group_by(reporter_code) %>%
  slice(1) %>%
  ungroup() %>%
  select(reporter_code, reporter)

partner_region <- read_xlsx("partner_region.xlsx", sheet = "Sheet1")

reporter_region <- merge(listreporter, partner_region, by.x = "reporter_code", by.y = "partner_code", all.x = T) %>% 
  select(reporter_code, partner_region) %>% 
  rename("reporter_region" = "partner_region")

port_data_TEU <- merge(port_data_TEU,partner_region, by.x = "partner_code", by.y = "partner_code", all.x = T) %>%
  relocate(partner_region, .after = partner_code) %>%
  rename(partner_region=partner_region)
  
port_data_TEU <- merge(port_data_TEU,reporter_region, by = "reporter_code", all.x = T) %>%
  relocate(reporter_region, .after = reporter_code) 

port_data_TEU$NENE_region <- ifelse(port_data_TEU$reporter_region == 'NE' & port_data_TEU$partner_region == 'NE', 1, 0)
sum(port_data_TEU$NENE_region)

port_data_TEU$SESE_region <- ifelse(port_data_TEU$reporter_region == 'SE' & port_data_TEU$partner_region == 'SE', 1, 0)
sum(port_data_TEU$SESE_region)

port_data_TEU$NESE_region <- ifelse(port_data_TEU$reporter_region == 'NE' & port_data_TEU$partner_region == 'SE', 1, 0)
sum(port_data_TEU$NESE_region)

port_data_TEU$SENE_region <- ifelse(port_data_TEU$reporter_region == 'SE' & port_data_TEU$partner_region == 'NE', 1, 0)
sum(port_data_TEU$SENE_region)

port_data_TEU$NEEX_region <- ifelse(port_data_TEU$reporter_region == 'NE' & port_data_TEU$partner_region == 'EX', 1, 0)
sum(port_data_TEU$NEEX_region)

port_data_TEU$SEEX_region <- ifelse(port_data_TEU$reporter_region == 'SE' & port_data_TEU$partner_region == 'EX', 1, 0)
sum(port_data_TEU$SEEX_region)

region_pair <- ec_undummy(port_data_TEU, c('NENE_region', 'SESE_region', 'NESE_region', 'SENE_region','NEEX_region','SEEX_region'), "region_pair", ref_level = "What") %>%
  select(port_code, partner_code, region_pair, year, quarter) 

port_data_TEU <- merge(port_data_TEU,region_pair, by.x=c("port_code", "partner_code", "year", "quarter"), by.y=c("port_code", "partner_code", "year", "quarter"))


# Add Control variables --------------------------------------------------------

load("berth_data.RData")
terminal_data <- berth_data
  
# add channel depth and cranes from World port index
wpi_data <- read.csv("WPI_data.csv")

# control variables
control_var <- merge(wpi_data, terminal_data, by.x="port_code",by.y="port_code", all = T) %>%
               select(port_code, 
                      year, quarter, quay_length, cranes, 
                      cranes_fixed, cranes_mobile, cranes_floating, max_lift, cargo_depth)


# merge with aggregated data
port_data_TEU <- merge(port_data_TEU, control_var, by.x = c("port_code", "year", "quarter"), by.y = c("port_code", "year", "quarter"), all.x = T) 


port_data_TEU$quay_length[port_data_TEU$quay_length==0] <- 100
port_data_TEU$cranes[port_data_TEU$cranes==0] <- 1

### Control variables for DID ####


controls <- c("cranes", "max_lift", "cargo_depth")
var_controls <- c("quay_length")

```

```{r include=F, message=FALSE, warning=FALSE}

#### Estimate ATT with not-yet-treated control group ####

port_data_TEU <- port_data_TEU %>% 
  group_by(port_code) %>% 
  mutate(port_id = cur_group_id(),
         mean_container=mean(container))

port_list <- port_data_TEU %>% filter(group!=0) %>% group_by(port) %>% summarize(id = mean(port_id))

attgt_cond_ny2 <- simple_staggered_did(yname = "container",            #outcome variable
                              tname = "period",                 #time variable
                              idname = "pair_id",                    #id for units (should be port_code*sender)
                              unitname = "port_id",
                              gname = "group",                    #grouping variable for first treatment. Is zero for never treated units)
                              xformula = controls,
                              varformula = var_controls,
                              control_group = "not_yet_treated",
                              data = port_data_TEU)


# putting together the results


results2 <- data.frame(Estimate = c("simple average", port_list$port[match(as.character(attgt_cond_ny2$groupwise_treatment_effects$id), port_list$id)]),
                       ATT = c(attgt_cond_ny2$average_treatment_effect$att,
                                   attgt_cond_ny2$groupwise_treatment_effects$att),
                       lower = c(attgt_cond_ny2$average_treatment_effect$att - attgt_cond_ny2$average_treatment_effect$crit_val,
                                attgt_cond_ny2$groupwise_treatment_effects$att - attgt_cond_ny2$groupwise_treatment_effects$crit_val),
                       upper = c(attgt_cond_ny2$average_treatment_effect$att + attgt_cond_ny2$average_treatment_effect$crit_val,
                                  attgt_cond_ny2$groupwise_treatment_effects$att + attgt_cond_ny2$groupwise_treatment_effects$crit_val),
                        p_value = c(NA, attgt_cond_ny2$groupwise_treatment_effects$pre_treatment_p_value))%>%
               mutate(sig = (ATT>0 & lower>0) | (ATT<0 & upper<0),
                      pretest = (p_value < 0.05) & !is.na(p_value),
                      across(c("ATT","lower","upper"), ~ format(round(.,digits=0), big.mark = ",")),
                      ATT = ifelse(sig==T, paste0(ATT, "*"), ATT),
                      ATT = ifelse(pretest==T, paste0(ATT, "^{x}"),ATT),
                      Conf = paste0("[",str_trim(lower),"; ",str_trim(upper),"]"))

results2 <- results2[c("Estimate", "ATT", "Conf")]

```


```{r include=F, message=FALSE, warning=FALSE}
#### Combining the results and producing a Latex table ####


# combining results
results_final <- cbind(results, results2[,c(2,3)]) 
colnames(results_final)[c(4,5)] <- c("ATT1","Conf1")



# putting together the results
results_gt_finalmente <- gt(results_final, rowname_col = "Estimate") |>
              tab_header(
                title = "Aggregated average treatment effects on container throughput from different origins",
                subtitle = "Control group: Never treated") |>
              cols_label(
                ATT="Extensive Margins",
                ATT1="Intensive Margins",
                Conf="95% CI",
                Conf1="95% CI") |>
              tab_stubhead(label = "")|>
              tab_row_group(label = "by group:",
                            rows = c(2:19)) |>
              row_group_order(groups = c(NA,"by group:")) |>
              sub_missing(columns = everything(),
                          rows = everything(),
                          missing_text = "") |>
              tab_footnote(footnote = "Confidence intervals are based on bootstrapped errors. ")


#generate Latex table
#add group row
results_final <- rbind(results_final[1,],c("by group", rep("", ncol(results_final)-1)) ,results_final[2:19,]) 

# Insert multirow cell into the appropriate position in the LaTeX code
addtorow <- list()
addtorow$pos <- list(nrow(results_final),1)
addtorow$command <- c("[2ex] \\hline \\hline \\multicolumn{5}{l}{\\shortstack[l]{Note: Dependent variable is number of partner ports per period\\\\ for the extensive margins estimation. Dependent variable is container\\\\ throughput per partner per period for the intensive margins estimation. \\\\Both estimations give the conditional ATT with not yet treated\\\\ control group. Superscript x indicates that we can reject the null of \\\\equal average pseudo.}}", 
                      "[1ex]")

# Modify the LaTeX code
latex_code <- print.xtable(xtable(results_final, caption = "Treatment effects on the extensive and intensive margins"),
                           label = "tab:separate_results",
                           caption.placement = "top",
                           include.rownames = FALSE,
                           add.to.row = addtorow,
                           hline.after = c(-1,-1,0, 2),
                           size = "\\begin{adjustbox}{max width=\\textwidth}")

latex_code <- gsub("Estimate & ATT & Conf & ATT1 & Conf1"," & \\\\multicolumn{2}{c}{Extensive margin} & \\\\multicolumn{2}{c}{Intensive margin} \\\\\\\\\n \\\\cmidrule(lr){2-3} \\\\cmidrule(lr){4-5} PTA & Cond. & 95\\\\% CI & Cond. & 95\\\\% CI" , latex_code)

latex_code <- gsub("\\\\end\\{tabular\\}", "\\\\end{tabular} \n \\\\end{adjustbox} \\\\label{tab:wochina_results}", latex_code)
latex_code <- gsub("by group", "\\\\emph{by group}", latex_code)
latex_code <- gsub("lllll", "lcccc", latex_code)
latex_code <- gsub("\\\\verb\\|\\^\\|\\\\\\{x\\\\\\}", "\\\\textsuperscript{x}", latex_code)

# Save modified LaTeX code to a .tex file
cat(latex_code, file = file.path(getwd(), "results_tables", "test.tex"))

```

```{r include=T, echo=FALSE}

results_gt_finalmente
```

